### ISSUE TITLE
Offline Installation of OpenSSH FOD

### ISSUE THREAD

**Issue by perithompson** [microsoft/Windows-Containers#119]
During an image-build process for kubernetes [#621](https://github.com/kubernetes-sigs/image-builder/issues/621) the install intermittently fails to download from the windows update server. without an FOD iso it is difficult to install OpenSSH in airgapped environments as the cab file is not available.  It would be good to have a location online to download Features on demand ahead of time and make them available locally to install on a windows 2019 image

**Comment by perithompson** [comment]
@immuzz let me know if i need to expand this at all?

**Comment by immuzz** [comment]
@perithompson could tell me the name of the binary so i could track down the owner?

**Comment by perithompson** [comment]
Hi muzz I'm not 100% sure but it's the openssh-server feature than you have to use add-windowscapability /online, which I believe downloads a cab in the background, I'll see if I can dig this out

**Comment by TBBle** [comment]
You're talking about https://github.com/PowerShell/Win32-OpenSSH, I think. Normally installed with:

```
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
```

Per [the FOD list](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-non-language-fod#openssh-server) that's `OpenSSH-Server-Package~31bf3856ad364e35~amd64~~.cab`.

There are [instructions](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-v2--capabilities#fod-repositories) for building a local FOD repository, you should be able to grab the FOD ISO for Server LTSC 2019 [from the Microsoft Evaluation Center](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19#-adding-capabilities-and-optional-packages-to-an-offline-wim-server-core-image) for example.

**Comment by perithompson** [comment]
Hi @TBBle, That is the package but that needs to reach out to the internet to get that update which can be unstable https://github.com/MicrosoftDocs/windowsserverdocs/issues/2074.  OpenSSH client is available on windows without using the online Microsoft catalog but SSH server is not, ideally having this included in windows isos along with the client would be amazing but if there was a place to manually download the cab and then add-windowscapability from that directory that would be a good workaround.  during an automated build process manually loading files to a c: before installing is ok but can be rather painful, especially for tools like https://github.com/kubernetes-sigs/image-builder

**Comment by TBBle** [comment]
The instructions I linked to above include how to use the FOD ISO as the source for `Add-WindowsCapability` (they use `DISM /AddCapability` but it's the same thing by a different name).

If you want to install a feature from a CAB file, you use `Add-WindowsPackage`, and must download the CAB file yourself. The OpenSSH-Server is a "monolithic" feature according to the FOD list, so it supports this, and so you should be able to just grab the `OpenSSH-Server-Package~31bf3856ad364e35~amd64~~.cab` from the FOD ISO.

That said, looking at the Windows Server 2019 FOD ISO on the Eval Centre, it appears to only contain _metadata_ for the OpenSSH-Server package, which makes sense since I think it's actually using the AppCompat system to support Windows 10 1809 FODs on Windows Server 2019. [This blog post](https://azurecloudai.blog/2019/11/22/offline-installation-of-openssh-server-on-windows-server-2019/) observed the same thing in late 2019, so I don't think this has changed recently.

So the ISO with the CAB will be the WIndows 10 Enterprise 1809 FOD ISO, instead, and you should be able to extract it from there, but I don't currently have access to a copy to check that.

One thing I will note is that the metadata I mentioned from the 2019 FOD ISO shows three packages for the OpenSSH.Server capability, two of which are shared with then OpenSSH.Client capability, so that might be why that blog post copies both client and server cabfiles, and it might also indicate that `Add-WindowsPackage` won't work and you will need to use `Add-WindowsCapability` with an appropriately-structured FOD repository.

As noted in [this blog post](https://plusontech.com/2019/04/22/how-to-add-features-on-demand-to-a-wim-file-without-the-fod-iso/) and [this blog post](https://www.nico-maas.de/?p=2287) you can do an install from Windows Update once and capture the CAB file for later reuse in local installs.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@immuzz, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@immuzz, @judyliu-ms, please provide an update or close this issue.

**Comment by judyliu-ms** [comment]
Hi @perithompson, apologies for the delayed response. I am checking in to see if @TBBle's comment was able to help resolve your issue?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@judyliu-ms, please provide an update or close this issue.

**Comment by fady-azmy-msft** [comment]
Closing due to staleness. @perithompson if you can provide more details/response to Judy's comment we can open this back up.
