### ISSUE TITLE
WAC opens visible docker command line window

### ISSUE THREAD

**Issue by WojciechThomas** [microsoft/Windows-Containers#121]
If I install on the same Windows Server WAC and containers, almost always WAC starts to display visible docker command line windows. 

Docker command line windows open and close quickly as I e.g. want to display a list of containers or images or longer if I download a new image. 

It makes work almost impossible as new command line windows flash at the front of the others windows.

![New command line windows appear when I switch from Certificates to Containers in WAC](https://user-images.githubusercontent.com/15376250/120967033-4fd74900-c767-11eb-8795-d8313205aa85.gif)

Currently, the only workaround I have found is to run WAC from the another computer.

**Comment by vrapolinario** [comment]
Hi @WojciechThomas, this is a known bug and we're working on getting a fix out.
This happens when you install WAC on the same container host you want to manage and opens a local session on that host.
As a workaround, you can do a few things:
- If you want to keep the local instance on the container host you can change the "Manage as" account (you can use the same account, just use the "manage as" option) on WAC's landing page.
- Still maintaining WAC installed on the same container host, you can open the browser session remotely, from Win10 or another server.
- You can install WAC on another machine and add the container host to the list of managed servers on WAC.

**Comment by WojciechThomas** [comment]
Hi @vrapolinario, I currently use your second solution.

I am surprised that this bug does not always appear. Until now I was not able to identify any conditions or patterns. It sometimes happens when I use the local administrator account, and sometimes when I use the domain administrator account, but generally it is a quite rare situation ;)

**Comment by vrapolinario** [comment]
The issue here presents when you're using single-sign on on WAC when it is installed on the same machine it is managing and calling an external tool, such as Docker. The dev team is fixing this bug and we should see an update soon.

**Comment by vrapolinario** [comment]
This is now fixed on an internal build and will go out soon.
