### ISSUE TITLE
how to "switch to windows containers" in winserver 2016

### ISSUE THREAD

**Issue by eric642** [microsoft/Windows-Containers#122]
On winserver2016, there is no docker desktop and dockerCli.exe, how to switch to windows container。

**Comment by vrapolinario** [comment]
Hi @eric642 have you checked our documentation on how to use Containers and Docker on Windows Server? https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server. Docker doesn't come pre-installed with Windows Server, but in the documentation we have the guides on how to get it installed and how to start using it.

Let us know if you have any recommendations on how to make the docs better or if the issue is with something else.

**Comment by eric642** [comment]
@vrapolinario , I have read this document。 But it didn’t tell me how to "switch to windows container" in winserver2016.
in the win10, i can swith to windows container.
![image](https://user-images.githubusercontent.com/19191915/121309059-4e0eb080-c934-11eb-8593-658fa62ea843.png)

**Comment by vrapolinario** [comment]
I see the confusion now. For Windows Server, there is no GUI such as in Docker Desktop. All interaction with Docker should be made via CLI, calling the command "docker", such as "docker run", "docker pull", etc.

On the other hand, you don't need to specify which type of container you are using - however, I should tell you that Linux containers are not supported on Windows Server. This has been an experimental feature in the past, but we did not continue on that path.

The only other thing you might need to specify is the isolation type. By default, the isolation type is process, but you can also provide --isolation=hyperv.
