### ISSUE TITLE
Include text editor on windows images

### ISSUE THREAD

**Issue by mikedennis** [microsoft/Windows-Containers#133]
This is something that is always a pain working with windows base images. 

I have to end up install chocolatey and then vim or something to just edit a configuration file. Never thought I would would wish back for the day when ```edit appsettings.config``` worked but surely you guys can put a simple to use basic text only editor on the images so these are easy to work with?

**Comment by lippertmarkus** [comment]
What's your use case? IMHO one main idea behind containers is immutability, so you create an image with your app and set configuration values either via mounting a config file or by using environment variables. Why do you want to edit a configuration while the container is running, instead of just restarting it with a different mounted config file or different environment variables?

If you need that for development with dev containers you may also just use a mount shared with the host.

**Comment by vrapolinario** [comment]
I second @lippertmarkus' comment on editing something on the container instance rather than the image. Can you please provide more details on the scenario?

**Comment by mikedennis** [comment]
It's 100% around troubleshooting but if the argument is to keep the image smaller (which hasn't been mentioned yet), I'm good with that. Windows images are so large already I wouldn't want them bloated significantly just for this. 

Telnet is another tool I often need but typically to solve that I just use a linux container in the same cluster then I can do /dev/tcp/x.x.x.x/y

**Comment by tigerinus** [comment]
Being able to edit a text file is so essential for troubleshooting.

Or at least there should be an effortless way to install an editor. People do `apk add nano` on Alpine Linux and `apt-get install nano` on Debian based Linux. There should be an equivalent for Windows containers.

**Comment by lippertmarkus** [comment]
You can install choco and just do an `choco install -y nano` in Windows containers as well if you really need to. Or like I mentioned above just mount files into the container and use your favorite text editor on the host.

**Comment by gopihc** [comment]
we are using vim with choco... whenever we need on container will install vim.
