### ISSUE TITLE
License for MicrosoftDockerProvider

### ISSUE THREAD

**Issue by magicmicah** [microsoft/Windows-Containers#135]
Hello,

Bit of a cross post from [here](https://github.com/OneGet/MicrosoftDockerProvider/issues/84) but we are hoping for clarification and support from the community to help us understand. We are interested in using the Microsoft Docker Provider provided below:

https://github.com/OneGet/MicrosoftDockerProvider

We have a few questions on this provider that we need to understand. What is the licensing for using DockerMsftProvider? Is this Docker CE? Is this Mirantis Container Runtime? We are evaluating this provider and we want to know that if we only run docker from this module, are there other licenses or restrictions that we should be aware of for running production workloads?

**Comment by thecloudtaylor** [comment]
The PowerShell model specifically (https://github.com/OneGet/MicrosoftDockerProvider) is provide under MIT. At present it only installs versions of the Mirantis Container Runtime, which is provided by Mirantis to Windows Server customers at no additional charge though an agreement between Microsoft and Mirantis. This agreement is not perpetual and could sunset in the future.

You could also use the open-source Moby project (Docker CE) - I am aware of customers/services that prefer that approach.

**Comment by mockjv** [comment]
@thecloudtaylor I just want to confirm that this is really the case because the current executables are signed by 'Docker, Inc.' and the versions of these executables are in sync with the current releases of dockerd.exe/docker.exe included with Docker Desktop (slightly, the versions published are behind Docker by about 2 minor versions at this point).
![Screen Shot 2021-08-31 at 10 54 30 PM](https://user-images.githubusercontent.com/15215338/131614675-733e8960-6178-46d4-8bb4-2b072c5586c4.png)

**Comment by slonopotamus** [comment]
You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install modern Docker engine for Windows containers on both Windows Server/Client.

**Comment by mockjv** [comment]
@slonopotamus Thank you so much for pointing me towards that project... I'll definitely be checking it out!
