### ISSUE TITLE
Windows host is not aware of container users

### ISSUE THREAD

**Issue by aravindhp** [microsoft/Windows-Containers#136]
When investigating [Windows Pod with RunAsUserName and a Projected Volume does not honor file permissions in the volume](https://github.com/kubernetes/kubernetes/issues/102849), it came to light that the Windows host is not aware of container users. This becomes important in the Project Volume scenario as the entities that are projected need to be assigned the correct user permissions. A resolution on how to handle this scenario is needed to fix the issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@brasmith-ms, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by brasmith-ms** [comment]
Hi folks, just an update here from discussions that happened over slack and in SIG-Windows a while back. This is by design with Windows containers. In general it is not recommended to mount the host file system into the container, especially when running as ContainerAdministrator. Where possible we recommend using HostProcess containers for administrative configuration, and then if host access is still necessary use the restricted ContainerUser account to access the host.
