### ISSUE TITLE
Memory leak on Isass.exe

### ISSUE THREAD

**Issue by zhiweiv** [microsoft/Windows-Containers#146]
Isass.exe uses a lot of memory and keeps increasing after upgrade AKS to latest release.
<img width="420" alt="Memory" src="https://user-images.githubusercontent.com/22001089/129310096-a0904818-5bdf-47eb-9267-6916518b58da.PNG">

Environment info:
```
C:\Users\zwliu>kubectl get node akswdjob000000 -o wide
NAME             AGE     VERSION   OS-IMAGE                         KERNEL-VERSION    CONTAINER-RUNTIME
akswdjob000000   2d20h   v1.21.2   Windows Server 2019 Datacenter   10.0.17763.2061   containerd://1.4.4+unknown
```
 It is only seen on the AKS Windows Containerd nodes.

We can provide the memory dump of Isass.exe if needed.

**Comment by AbelHu** [comment]
cc @kevpar @mainred @bingbing8

**Comment by immuzz** [comment]
@zhiweiv can you provide us the memory dump and also traces using WTR.

**Comment by mainred** [comment]
@zhiweiv thanks for your report, this issue seems not to be stably reproduced, please provide the necessary memory dump and also traces using WTR by for example, `wpr -start "C:\Program Files\containerd\ContainerPlatform.wprp" -start diskio -start fileio  -start CPU` for Windows containerd node

**Comment by zhiweiv** [comment]
https://1drv.ms/u/s!Al_DGOKCXcMSkGojHci7jxf-WA7D?e=ojkGvn is the memory dump I collected in the issue first seen. 

I can provide the trace when it reproduces again after my vacation. For the trace I have few questions.
1. Should I enable the trace at the beginning after vm restart?
2. If the Isass.exe is already taking memory and keep increasing. Then I enable trace for a few minutes and stop it, does this work?
3. Will the trace generate a file I can collect to share?

**Comment by mainred** [comment]
Hi @zhiweiv , we want the trace files collected **throughout the issue**, the normal ways to collect the issue are as follows:

- Start to record system performance
`wpr -start "C:\Program Files\containerd\ContainerPlatform.wprp" -start diskio -start fileio -start CPU`
- reproduce the issue
- stop recording
`wpr -stop wpr_trace.etl`

You'll find the wpr_trace.etl located under your current directory.

> If the Isass.exe is already taking memory and keep increasing. Then I enable trace for a few minutes and stop it, does this work?

For our case, I am not sure when memory consumption is piling up, but that will be great if we can capture as many events as possible. The defect is that the trace file might be huge.

BTW, do you mind sharing the setup of your cluster, like workloads and fqdn, if possible? so that we can try to reproduce the issue?

**Comment by zhiweiv** [comment]
This is not reproduced on our all containerd nodes too, I only found a few nodes with this memory leak. I have removed all workloads from containerd nodes due to a couple problems found in containerd(reported in AKS repo). I will try to find the repro steps and get the trace when I come back to office.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhiweiv** [comment]
After upgraded to latest Windows image, we only see one Isass.exe which memory increased to 60MB in 3 days. It is accepted so far. I will keep monitoring the memory usage.

**Comment by zhiweiv** [comment]
No high memory usage of Isass.exe after Windows upgrade.
