### ISSUE TITLE
Testing Windows applications within containers

### ISSUE THREAD

**Issue by ghost** [microsoft/Windows-Containers#148]
My startup is building a windows application with UI, during the testing phase we would like to run apps in a container, test them and push to production.
We are new in testing, so is there a framework or some tools to run a GUI app in container and interact with them from Powershell (click a button on the app, open a notepad, etc) ?

**Comment by vrapolinario** [comment]
This topic has been discussed extensively on this issue: https://github.com/microsoft/Windows-Containers/issues/47
Adding @richlander from the .Net team to see if they have any updates, and @weijuans-msft from Windows container side. I don't think we have an update, but it's still worth track customer requests on it.

**Comment by jedieaston** [comment]
This would be extremely handy for winget package testing. I've looked into using Krypton directly (which is what the Sandbox uses for fastboot Windows micro-VMs), but there doesn't seem to be any documented APIs for it.

**Comment by ghost** [comment]
> This would be extremely handy for winget package testing. I've looked into using Krypton directly (which is what the Sandbox uses for fastboot Windows micro-VMs), but there doesn't seem to be any documented APIs for it.

What is Krypton?

**Comment by jedieaston** [comment]
It's one of the types of Windows containers. [This](https://www.youtube.com/watch?v=rIfH8ouEctk) is the only official documentation they've updated lately on it, but it's basically a isolated microVM (similar to Firecracker, if you're familiar with Linux microVMs) that runs on Hyper-V and can start super fast. It's used for Edge Application Guard, WSL2, and the Windows Sandbox. They won't let you start your own for some reason, even if you dig into the API.

**Comment by cwilhit** [comment]
Closing this thread in favor of #47, and will reopen that issue to track feature requests related to UI automation in Windows containers.

**Comment by xlazom00** [comment]
I did investigate this issue for a while and I did found that problem is in UIAutomation.
so https://github.com/microsoft/winappdriver don't work.
And if your testing framework use UIAutomation it don't work.

But I did add something like winappdriver directly into my app.
Selenium webdriver server so my application has selenium driver api.
And all works as expect. 
So if your target is to test own application inside windows containers you can do that.

I can see whole app with tree of items,....
I can click on items, edit text,....
I can see app with screenshots(selenium has api) 
window handles also working so you can see dialogs.
It is also working with system dialogs (open, save files, font picker,...)
I did add something like inspector into server so I can control whole app from browser.
