### ISSUE TITLE
Unable to pull 2022 images on 21H1 W10 Pro

### ISSUE THREAD

**Issue by rosskirkpat** [microsoft/Windows-Containers#155]
OS Name:  Microsoft Windows 10 Pro 
OS Version: 19043.1165

```powershell
 docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022
ltsc2022: Pulling from windows/nanoserver
no matching manifest for windows/amd64 10.0.19043 in the manifest list entries

docker pull mcr.microsoft.com/powershell:lts-nanoserver-ltsc2022
lts-nanoserver-ltsc2022: Pulling from powershell
a Windows version 10.0.20348-based image is incompatible with a 10.0.19043 host

```

**Comment by vrapolinario** [comment]
We just publish information about this: https://techcommunity.microsoft.com/t5/containers/windows-server-2022-and-beyond-for-containers/ba-p/2712487#M139 - Please see the Windows and developer scenarios section on the blog post.

Here's the long story: Windows 10 has a build number of 19043. Windows Server 2022 has a build number of 20348, so that means the image is newer than the host. We never supported this scenario, but it means customers running Windows 10 can't pull or run Windows Server 2022 images. Customers running Windows 11, which has a higher build number than Windows Server 2022 can. Since Windows 11 is not GA yet, we know many customers don't have an option to move up, so we're temporarily enabling these new preview images for Windows 10 21H1 so you can kick the tires until Windows 11 is GA.

**Comment by JoelLeach** [comment]
The [Windows Container Version Compatibility ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1) page shows that you can run a Windows Server 2022 image on Windows 10 21H1 via Hyper-V isolation.  Is that info now out of date?
