### ISSUE TITLE
Collecting use cases for Windows Server 2022 on AKS and AKS-HCI

### ISSUE THREAD

**Issue by weijuans-msft** [microsoft/Windows-Containers#162]
As I outlined in this blog when we announced GA of Windows Server 2022 (aka.ms/ws2022gacontainerblog), we are actively working with Kubernetes community to bring up Windows Server 2022 support there and then enable the support on AKS and AKS-HCI. I am curious to see from this community what use cases you have to use Windows Server 2022 on AKS and AKS-HCI.

**Comment by awakecoding** [comment]
One thing I would like to know is how one could use Windows Server 2022 + AKS-HCI to run a traditional ASP.NET Windows Server application that requires SQL Server, since SQL Server does not have an official Windows container, only a Linux container.

**Comment by zhiweiv** [comment]
We'd like the smaller image size which can speed up the Windows node pool scale/upgrade.

Another one is HCS improvement per https://github.com/microsoft/hcsshim/issues/919#issuecomment-894127776, we saw a dozen of hcs erros in our environment, hope this gets improved in Windows Server 2022.

**Comment by pbering** [comment]
We have multiple clients that uses AKS with both Linux and Windows pools as we have a lot of classic ASP.NET 4.x applications that needs Windows/IIS. We want to develop on Windows 11 and host in AKS on Windows Server 2022 node pools so we are able to both use the same OS version AND to be able to run in process isolation on our workstations. Also looking forward to smaller images!

**Comment by weijuans-msft** [comment]
> One thing I would like to know is how one could use Windows Server 2022 + AKS-HCI to run a traditional ASP.NET Windows Server application that requires SQL Server, since SQL Server does not have an official Windows container, only a Linux container.

Curious: why do you need SQL Server in a container? Can you use Azure Arc enabled Data Service? See more in this blog:
https://techcommunity.microsoft.com/t5/itops-talk-blog/azure-arc-enabled-data-services-with-azure-stack-hci-and-azure/ba-p/2751893.

**Comment by awakecoding** [comment]
> > One thing I would like to know is how one could use Windows Server 2022 + AKS-HCI to run a traditional ASP.NET Windows Server application that requires SQL Server, since SQL Server does not have an official Windows container, only a Linux container.
> 
> Curious: why do you need SQL Server in a container? Can you use Azure Arc enabled Data Service? See more in this blog: https://techcommunity.microsoft.com/t5/itops-talk-blog/azure-arc-enabled-data-services-with-azure-stack-hci-and-azure/ba-p/2751893.

I am evaluating if Windows Server 2022 + AKS-HCI would be suitable as a deployment option for [Devolutions Server](https://server.devolutions.net/). Rather than let our customers figure out how to do it, I wish to see if it makes sense, and how we could officially support it. Devolutions Server is a traditional ASP.NET application that uses SQL Server on Windows Server, and the vast majority of deployments are entirely self-hosted, with some of them without access to the internet, which is why I wouldn't consider anything hybrid as a hard requirement.

Now we can all agree that "regular" SQL Server deployments would likely be done the traditional way, especially for high availability deployments. The issue isn't necessarily there: if a customer has AKS-HCI and wants to evaluate our product, it should be possible to make a quick deployment that doesn't involve a "regular" SQL Server. The biggest obstacle to a successful onboarding in Devolutions Server has always been the installation and configuration of SQL Server, if it could be containerized, then it would solve a HUGE problem for us.

Customers aren't necessarily DBAs and don't specifically care which database we use, when we're just trying to onboard them, we often have to assist them through the procedure in support calls, and it takes a long time to do. A simple containerized SQL Server would be trivial to automate at least for initial/small deployments and solve the onboarding problem entirely. Customers could then migrate to a regular SQL server deployment after if they ever need to. Most would be happy with automated regular backups in case the database container crashes and corrupts the data.

The other reason why I would like an SQL Server *Windows* container is because it's the only way we could hope of getting gMSA support for a containerized SQL Server, something which will realistically not happen for Linux containers in the foreseeable future. Even without gMSA, I don't see why we couldn't get a Windows container that has exactly the same features  as the Linux container, just for the sake of running it on Windows along the rest.

Please keep in mind the starting point: self-hosted ASP.NET application in IIS + SQL Server on Windows Server. This is the kind of deployment that is most frequently entirely on-premises, and sometimes disconnected from the internet. When deployed in Azure, it's inside an Azure VM, possibly with an Azure SQL Server instance.

Can Windows Server 2022 + AKS-HCI be used in a way that makes sense for these types of deployments?

**Comment by brobichaud** [comment]
We are very eager for the smaller base image sizes to make our deployments more smooth. We also have a strong need for the new Server container image. And finally but still very important to us is that we want to be on the latest Windows Server release both from a peace of mind and outward positioning perspective. It looks lame from a marketing perspective to indicate you're on an old version of a core piece of infrastructure.

**Comment by weijuans-msft** [comment]
@brobichaud thanks for sharing. Are you going to run on AKS?

**Comment by brobichaud** [comment]
> @brobichaud thanks for sharing. Are you going to run on AKS?

Yes @weijuans-msft we do currently and intend to continue hosting much of our containerized workloads in AKS clusters. We'd very much like for AKS to be on the leading edge of support for Windows container deployments.

**Comment by cmendible** [comment]
Hi Team, have FSI and Retail customers who uses AKS and also have many "legacy" .NET applications which require IIS and in some cases full Windows Server images. They need Windows Server 2022 as host, not only to deploy and run those workloads, but to be able to use Windows 11 for development without compatibility / versioning issues. 

Given that compatibility with upstream k8s was tested with [99.6% pass rate](https://techcommunity.microsoft.com/t5/containers/contain-your-excitement-updates-on-windows-server-2022-and/ba-p/2820015), is there an ETA for this feature?

Thanks!

**Comment by artisticcheese** [comment]
There are some issues seems to be fixed in Win2022 but not Win2019, see below as example. Another use case for WS2022 on AKS
https://github.com/microsoft/Windows-Containers/issues/202

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by ohault** [comment]
This is neither one, nor two, but a set of use cases that you can see as the key strategic step to move forward beyond Windows Server by supporting all obvious [Windows server roles](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-roles-and-services) as containers to run on AKS (all flavors of AKS including Edge). 

A first approach would be to have redefined containers provider by Microsoft similar to Windows Containers base images (Active Directory Domain Services, File and Storage services, DNS Server, DHCP Server, ...).

The next step, would open the way to be able to package yourself (IT department, ...), your own images with Windows server feature, either by building it (e.g. BuildKit) or re-configuring an existing image (adding/removing all required/unrequired features) from a given existing "Windows server" based image for Windows Containers.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, please provide an update or close this issue.
