### ISSUE TITLE
Support File Server (SMB) In Windows Container

### ISSUE THREAD

**Issue by Dannygbond** [microsoft/Windows-Containers#165]
An important feature, which can save a lot of trouble, along with huge ease in The technological aspect. Creating dedicated nano servers for Filesharing in classes, workspaces, etc...

**Comment by ohault** [comment]
Indeed and an interesting point would be to analyse it in the perspective of vSMB implementation part of the currently single Tenant approach of Windows Sandbox.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, @judyliu-ms, please provide an update or close this issue.

**Comment by judyliu-ms** [comment]
This has been added to our backlog, for internal ADO tracking: Scenario #37316096. 

To help us prioritize, do you mind expanding on your use case @Dannygbond? What environment are you running in? (standalone, AKS etc.)

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, @judyliu-ms, please provide an update or close this issue.

**Comment by rrmistry** [comment]
Hi @judyliu-ms , @weijuans-msft ,

Our sincere apologies for being persistent, but this is a huge business blocker for us.

We are eager start discussions about our use case for services like SMB (https://github.com/microsoft/Windows-Containers/issues/165) / BFE (https://github.com/microsoft/Windows-Containers/issues/173), and learn about the long term vision of the Windows Container team.

_________________________

Fortunately, we've been able to make progress by leveraging the Windows Host Process Feature ([K8s Docs](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/) / [MSFT Docs](https://docs.microsoft.com/en-us/azure/aks/use-windows-hpc)) on AKS with K8s version `1.23.5`.

💖 What's awesome is that using host process containers on AKS Windows Node Pools we can access these needed host kernel services to setup SMB shares and Windows Firewall Rules from within the container process!

💔 What's unfortunate is that host process containers feature does not seem to work yet with gMSA accounts, which is the main driver for us to switch away from domain joined Azure VMs.

The challenge now is to assess or assist in getting host process containers to work with gMSA accounts!

_________________________

Offline discussions at win-containers@microsoft.com would help us plan our business needs and expectations.

Looking forward to hearing soon, and thank you all for all your continued efforts and hard work!

The efforts are noticed and appreciated! 🙏

CC: @fady-azmy-msft , @cwilhit , @msuthar09

**Comment by fady-azmy-msft** [comment]
Hey @rrmistry , could you share more about the workload or the use-case you have for wanting gMSA support for host process containers?

**Comment by ohault** [comment]
Hey @fady-azmy-msft, easy, one key use case is to support multi-tenancy

**Comment by rrmistry** [comment]
Hi @fady-azmy-msft ,

Our use case is we are trying to use `host process containers` as a stop-gap solution to get access to host services like SMB (https://github.com/microsoft/Windows-Containers/issues/165) / BFE (https://github.com/microsoft/Windows-Containers/issues/173) which are currently disabled in Windows Containers.

We also need domain authentication to access services like NTFS permissions on SMB shares / SQL Server with Windows Authentication, etc. The `gMSA` architecture fit the domain authentication requirements nicely by not requiring domain-joined containers.

The problem seems that at the moment, we can only have `host process containers` or `gMSA containers`, but not both.

We are trying various hacks like network-only user-impersonation in `host process containers`.

For example:
```powershell
runas /netonly /user:DOMAINNAME\USERNAME powershell -File <K8S_ConfigMap_File_Mount_Path> ...
```

But this seems like an anti-pattern and would like to avoid using `host process containers` as a stop-gap solution in general.

As mentioned in this comment: https://github.com/microsoft/Windows-Containers/issues/173#issuecomment-1140317753, we are trying to modernize a legacy 3rd party Windows application that has many hard-coded checks that we can't disable. One check is it needs Named Windows Firewall Rules to exist or it immediately stops. It also sets up SMB shares per node in Azure VMs use case.

Containerizing this application needs at a minimum:

1. Access to services for Windows Firewall like `BFE` within the container
2. Access to services for SMB shares like `LanManServer` + `LanManWorkStation`

Both of which are currently not enabled.

_____

Tragedy is that even if these services are available today in latest Windows Containers, it is still some time before AKS enables Windows Server 2022 Node Pools https://github.com/Azure/AKS/issues/2115 to become Generally Available to leverage newer images.

So everything needs to be planned out.

**Comment by brasmith-ms** [comment]
Hey @rrmistry, from the HostProcess container side of things we have added support for running as custom user accounts, although I am not entirely sure this adds dedicated support for gMSA as we did not design around that. 

PR with this change: https://github.com/microsoft/hcsshim/pull/1286

If you use the latest containerd nightly build you should be able to test this out with HPCs.

**Comment by 0xada4d** [comment]
Hi - I see this issue has been marked as completed, but can someone verify that File Server (SMB) is now available in Windows Containers? I'm having trouble with this in my testing.

**Comment by incapdns** [comment]
@0xada4d No, its not compatible.
