### ISSUE TITLE
Windows containers do not allow changing resolution

### ISSUE THREAD

**Issue by jwielebnowski** [microsoft/Windows-Containers#174]
It is important that we can set a higher resolution on the container for capturing high resolution images on a headless graphics applications. However currently available windows containers do not allow updating their resolutions. I have tried a few and all of the start in 1024x768 resolution.

This is example from running windows container mcr.microsoft.com/windows:2004

Current resolution:
![Current Resolution](https://user-images.githubusercontent.com/8700191/138952090-4b919f03-7a22-4a71-b5c4-8835018050ce.PNG)
List of supported modes:
![Supported Modes](https://user-images.githubusercontent.com/8700191/138952142-c285d216-7f8d-4a95-854f-9a6c14731e1e.PNG)
Error when trying to set the new resolution
![Mode not supported](https://user-images.githubusercontent.com/8700191/138952184-934a7da1-5c14-41ab-b45e-bdba6f06516d.PNG)

I am using QRex.exe 
[QRes.zip](https://github.com/microsoft/Windows-Containers/files/7421195/QRes.zip)

I have also wrote a simple C++ that does not work on containers but works fine outside.

**Comment by adamrehn** [comment]
@jwielebnowski I can see from the filesystem path in your screenshots that your application is using the Unreal Engine. In this case, there is no need to modify the resolution at a system level since you can simply specify a resolution via your application's command-line flags, like so:

```
MyProject-Cmd.exe -stdout -FullStdOutLogOutput -unattended -RenderOffscreen -windowed -ResX=1920 -ResY=1080 -ForceRes
```

If you haven't already read through the blog post [Offscreen rendering in Windows containers](https://unrealcontainers.com/blog/offscreen-rendering-in-windows-containers/) on the Unreal Containers community hub then I'd recommend taking a look, since it discusses a number of considerations for headless rendering with the Unreal Engine in Windows containers.

**Comment by jwielebnowski** [comment]
@adamrehn

I have tried your suggestion before posting here. Unfortunately that solution does not work on windows containers beyond the container fixed resolution. However, the difference might be that my issue is in regards to the pixel streaming where the video frame is fixed at the maximum of the container resolution.

**Comment by adamrehn** [comment]
@jwielebnowski did you include all of those flags? (Specifically, `-windowed` and `-ForceRes` are useful to force the Unreal Engine to use a higher resolution than the monitor supports.)

**Comment by jwielebnowski** [comment]
@adamrehn 
Yes I did. There is also another problem with that approach in regards to the pixel streaming. The resolution of the game has to be adjusted all the time at the runtime during pixel streaming. In 4.27 you can directly adjust the resolution of the game through the UICommand but again it fails on the container if you try to go beyond the container resolution.

**Comment by adamrehn** [comment]
In that case, this sounds like an Unreal Engine limitation that needs to be addressed. I'd recommend filing a ticket on the [Unreal Developer Network (UDN)](https://udn.unrealengine.com/).

**Comment by vrapolinario** [comment]
Sorry for the delay.
Let us know if the suggestion above worked. Also, if possible, please try out the new Server image instead of the Windows one.

**Comment by jwielebnowski** [comment]
@vrapolicario All the above suggestions do not work in Unreal. However, we have found the way to work around the problem so that is good. Having said that, it would be nice to get an answer regarding your containers. Is there a reason that changing the resolution in the container does not work? Is it a defect or is it OS limitation that makes it unable to implement?

**Comment by cwilhit** [comment]
@jwielebnowski that the resolution is a constant is due to the nature of Windows containers. Windows containers run in a session akin to the "session 0" that Windows boots and services predominantly run in (console-only). When users connect to a Windows machine either over RDP or from the Windows login screen, users are put into an interactive session (non-"session 0") where there's the Windows Desktop Manager handles things like compositing. Windows container images don't ship with this.

It's good to hear you found a workaround (curious to know, what was it?). If you'd like to make a request for Windows containers to formally support resolution changing, we can track that request with this issue, otherwise I will go ahead and close it.

**Comment by cwilhit** [comment]
Closing this issue as a resolution for the problem has been reached. I've provided an explanation for the current architectural limitations, and if there is interest in Microsoft doing additional work, please respond on this and we can reopen to track the ask.
