### ISSUE TITLE
Docker Engine 20.10.9 and higher for the DockerMsftProvider are missing

### ISSUE THREAD

**Issue by ilanitr** [microsoft/Windows-Containers#183]
The DockerMsftProvider OneGet provider's metadata at [https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json](https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json) does not yet have any 20.10.9 or higher releases, even though [https://github.com/moby/moby](https://github.com/moby/moby) is up to [20.10.11](https://docs.docker.com/engine/release-notes/).

Version 20.10.11 handles ambiguous OCI manifest parsing to mitigate CVE-2021-41190 as well as other Windows related fixes was released on 2021-11-17.

I see that DockerMsftProvider was last updated on 2021-10-29 with version 20.10.8 that was released on 2021-08-03.

**Comment by pjh** [comment]
cc @jsturtevant @marosset @immuzz for K8s sig-windows - do you know anybody who can help make the latest Docker version available via DockerMsftProvider?

**Comment by brasmith-ms** [comment]
Hi @ilanitr @pjh, the releases of the docker engine enterprise and Moby are not totally in sync. Mirantis handles the release of docker engine (now named the Mirantis Container Runtime), and DockerMsftProvider simply ingests and signs those releases for Azure. See the latest releases from [Mirantis here](https://docs.mirantis.com/mcr/20.10/rn-20-10.html).

Additionally, the DockerMsftProvider [is being deprecated](https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799) next year in favor of containerd, Moby, or direct installation of the Mirantis Container Runtime.

**Comment by pjh** [comment]
@brasmith-ms thanks for explaining the situation here and also in the Kubernetes SIG-Windows meeting today. We came across one other option: there is some [Docker documentation](https://docs.docker.com/engine/install/binaries/#install-server-and-client-binaries-on-windows) describing how to install Docker Engine directly from binaries available at https://download.docker.com/win/static/stable/x86_64/. Do you happen to know anything about those binaries, like who is building them and what code base they're from?

The most recent docker versions are present there, but we're not entirely sure of their origin.

**Comment by liyanhui1228** [comment]
Just follow up here, I noticed that Mirantis has released [20.10.9](https://docs.mirantis.com/mcr/20.10/rn-20-10/20-10-9.html) which contains the CVE fix for CVE-2021-41190, but it's not downloadable from the DockerMsftProvider yet. Is there anything missing to make it downloadable?

**Comment by TBBle** [comment]
Per https://github.com/microsoft/Windows-Containers/issues/99#issuecomment-807019756, that's entirely in Mirantis' hands. I'll tag @james-nesbitt as the person who followed-up last time this sort of question was raised.

**Comment by slonopotamus** [comment]
You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install modern Docker engine for Windows containers on both Windows Server/Client.

**Comment by liyanhui1228** [comment]
Just verified that docker 20.10.9 is available in the MS provider now, which contains the CVE fixes for CVE-2021-41190. We could probably mark this issue as fixed.

**Comment by madduci** [comment]
Hi

would it be possible to get newer Versions?

**Comment by TBBle** [comment]
Not from here, I suspect. DockerMsftProvider was [intended to be dropped in September 2022](https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799), although that's been pushed back to [30 April 2023](https://techcommunity.microsoft.com/t5/containers/important-update-deprecation-of-docker-virtual-machine-images/ba-p/3646272).

Since [Mirantis announced taking over support for Docker EE from MSFT in September 2021](https://web.archive.org/web/20220629005012/https://www.mirantis.com/blog/windows-server-container-users-mirantis-is-here-to-support-you/), the installation instructions in [the documentation](https://learn.microsoft.com/en-au/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1) have changed to https://www.mirantis.com/docker-engine-enterprise-support/. The "30 April 2023" link and the docs also have some alternative methods of getting Moby (formerly Docker CE) installed on Windows Server.

Note that you only have until the end of April to acquire perpetual free licenses for MCR (formerly Docker EE) on Windows Server, see https://www.mirantis.com/docker-engine-enterprise-support/.
