### ISSUE TITLE
Nanoserver open Port to incoming TCP traffic

### ISSUE THREAD

**Issue by pjohnst5** [microsoft/Windows-Containers#184]
### How can I open a port on `mcr.microsoft.com/windows/nanoserver:10.0.14393.1066` for incoming TCP traffic?

I've downloaded the docker image nanoserver `mcr.microsoft.com/windows/nanoserver:10.0.14393.1066` and I'm trying to open up a port (443 specifically) to allow incoming TCP traffic

The way I've seen this be done i[n blogs](https://www.ntweekly.com/2016/11/10/open-or-block-firewall-ports-on-windows-nano-server-2016-using-powershell/) and stuff is either:

`Set-NetFirewallRule -Name FPS-ICMP4-ERQ-In -Enabled False`
or 
`netsh advfirewall firewall add rule name="Open port 443" protocol=TCP localport=443 action=allow`

However, `Set-NetFirewallRule` is part of the powershell module[ `NetSecurity`](https://docs.microsoft.com/en-us/powershell/module/netsecurity/?view=windowsserver2019-ps) and when I tried to install that ([post](https://activedirectorypro.com/install-powershell-modules/)) on nanoserver, I got errors:
```
PS C:\usr\local\runner\webapp> Import-Module NetSecurity
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
At line:1 char:1
+ Import-Module NetSecurity
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

```

And `netsh advfirewall` or `netsh firewall` also could not be loaded ([stack overflow post](https://superuser.com/questions/430414/netsh-advfirewall-command-not-found)):
```
PS C:\usr\local\runner\webapp> netsh add helper  AUTHFWCFG.DLL
The following helper DLL cannot be loaded: AUTHFWCFG.DLL.

PS C:\usr\local\runner\webapp> netsh add helper  FWCFG.DLL
The following helper DLL cannot be loaded: AUTHFWCFG.DLL.
The following helper DLL cannot be loaded: FWCFG.DLL.
```

What's any way to open up a port on Nanoserver for incoming TCP traffic?

**Comment by vrapolinario** [comment]
Have you mapped the ports from the container host to the container? Please check the documentation here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture

**Comment by daschott** [comment]
I think the blog post might not be referring to nanoserver container image, but Nanoserver as the server OS?

Is it possible to update to newer OS version such as Windows Server 2019? The default has changed to be "Allow all" since Windows Server 2019:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-isolation-security#windows-server-containers

On Windows Server 2019 and above, in a Dockerfile, you can add:
```
FROM mcr.microsoft.com/windows/nanoserver:10.0.14393.1066
EXPOSE 443
```
If you don't want to touch the Dockerfile, then you can use `--expose 443` flag instead. This will open up the container port 443. 

If you want to publish internal container port 443 on the host for external access, then you can use [-p option](https://docs.docker.com/config/containers/container-networking/#published-ports)
```docker run -p <host_port>:443 <my_image>```

If you are using Windows Server 2016, you may need to add an additional allow rule on the container host. Which network mode is being used here?

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, @daschott, please provide an update or close this issue.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@weijuans-msft, @daschott, please provide an update or close this issue.

**Comment by cwilhit** [comment]
@pjohnst5 does David's reply above answer your question / are you still stuck on this issue?

**Comment by cwilhit** [comment]
Closing due to staleness. Will reopen if new info comes in.
