### ISSUE TITLE
docker --pid parameter silently ignored

### ISSUE THREAD

**Issue by changov** [microsoft/Windows-Containers#189]
I'm experimenting with Docker version 20.10.7, build 40ef3b6, on Windows Server 2022. I wanted to try a container with shared pid namespace, per https://docs.docker.com/engine/reference/run/#pid-settings---pid. However, it appears both the `host` and `container` options are silently ignored: The container is created with its own pid namespace, and it gets the usual bunch of CExecSvc, svchost, and csrss companion processes. Sample command:

`docker run -it --rm --name joined_pidspace --pid=container:test 136110e1a05c powershell`

If I put a non-existent container name in the pid param, the command still runs. This makes me suspect --pid is not implemented on Windows. Searching the web broadly could not confirm pid namespace sharing works on Windows but turned up this complaint about the same issue: https://github.com/docker/for-win/issues/4868.

**Comment by cwilhit** [comment]
Hi @changov, Windows containers don't support sharing process spaces between them. It's not something that we support today in the OS. This is required before a container runtime such as Docker could ever in turn expose the feature. 

Care to share more about what you are trying to do in Windows containers that would require having shared PID spaces?

**Comment by changov** [comment]
No practical problem (yet). Just exploring capabilities. Much of the containers documentation sets expectation of such pid namespace sharing to work. :-) It'll be good to at least update the Windows-specific documentation about the limitation and make Docker fail explicitly instead of silently ignore the parameter.

Incidentally, Kubernetes supports pods on Windows. What is the extent of the "namespace" sharing in that case? Networking is obviously supported. How about shared memory, IPC mechanisms, synchronization objects?

**Comment by cwilhit** [comment]
In the case of pods, networking namespace is the only thing that can be shared. Shared mem, sync objects, etc. we don't currently support. For IPC, you can do things like: mapping named pipes, mapping shared files, anything that goes over the network (like WCF over TCP).

Say, these are all things that I think folks would benefit from having documented. Making a mental note for my team😀📝. Since you're not asking for shared PID spaces as a feature request, I am going to change the issue tag to "documentation" and take the action to get some docs up on aka.ms/containers that describes the current state of affairs, geared towards this stuff for prospective Windows container developers.

**Comment by cwilhit** [comment]
Closing this issue out since we've added some additional documentation (with more to come) regarding the above [under this page on our docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container#what-gets-isolated).
