### ISSUE TITLE
Session affinity is not being honored for service

### ISSUE THREAD

**Issue by artisticcheese** [microsoft/Windows-Containers#194]
My service is defined as below, it specifies both  `"sessionAffinity": "ClientIP"` and `"externalTrafficPolicy": "Local"`. My expectations are with this setup traffic coming from single external IP address will always end up on the same pod, it's not working as expected.
Server version `Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`

```json
PS C:\Users\artis> k get service esb-api-service -n qa -o=jsonpath='{.spec}'
{
   "clusterIP": "192.168.0.246",
   "clusterIPs": [
      "192.168.0.246"
   ],
   "externalTrafficPolicy": "Local",
   "healthCheckNodePort": 32675,
   "ports": [
      {
         "name": "http",
         "nodePort": 30900,
         "port": 80,
         "protocol": "TCP",
         "targetPort": 80
      },
      {
         "name": "https",
         "nodePort": 31041,
         "port": 443,
         "protocol": "TCP",
         "targetPort": 443
      }
   ],
   "selector": {
      "app": "esb-api"
   },
   "sessionAffinity": "ClientIP",
   "sessionAffinityConfig": {
      "clientIP": {
         "timeoutSeconds": 10800
      }
   },
   "type": "LoadBalancer"
}
```
I have 2 pods running on single node for that application below
```powershell
PS C:\Users\artis> k get pods -n qa -l app=esb-api -o wide
NAME                       READY   STATUS    RESTARTS   AGE    IP           NODE              NOMINATED NODE   READINESS GATES
esb-api-649875cf66-bgqg9   1/1     Running   0          33m    10.1.0.50    akswinpl1000002   <none>           <none>
esb-api-649875cf66-lf4w9   1/1     Running   0          6h6m   10.1.0.228   akswinpl1000002   <none>           <none>
```
I expected that incoming traffic will be going to single pod based on incoming client IP address but traffic is in fact load balanced accross both PODs. Servers are output actual pod name inside HTTP header and it's showing being balanced between both pods

```powershell
PS C:\Users\artis> (invoke-webrequest http://core360esb-api-qa.northcentralus.cloudapp.azure.com/docs/EmailTemplate.html -Method HEAD).Headers.SN
esb-api-649875cf66-lf4w9
PS C:\Users\artis> (invoke-webrequest http://core360esb-api-qa.northcentralus.cloudapp.azure.com/docs/EmailTemplate.html -Method HEAD).Headers.SN
esb-api-649875cf66-lf4w9
PS C:\Users\artis> (invoke-webrequest http://core360esb-api-qa.northcentralus.cloudapp.azure.com/docs/EmailTemplate.html -Method HEAD).Headers.SN
esb-api-649875cf66-bgqg9
PS C:\Users\artis> (invoke-webrequest http://core360esb-api-qa.northcentralus.cloudapp.azure.com/docs/EmailTemplate.html -Method HEAD).Headers.SN
esb-api-649875cf66-lf4w9
PS C:\Users\artis> (invoke-webrequest http://core360esb-api-qa.northcentralus.cloudapp.azure.com/docs/EmailTemplate.html -Method HEAD).Headers.SN
esb-api-649875cf66-lf4w9
PS C:\Users\artis> (invoke-webrequest http://core360esb-api-qa.northcentralus.cloudapp.azure.com/docs/EmailTemplate.html -Method HEAD).Headers.SN
esb-api-649875cf66-bgqg9
PS C:\Users\artis> (invoke-webrequest http://core360esb-api-qa.northcentralus.cloudapp.azure.com/docs/EmailTemplate.html -Method HEAD).Headers.SN
esb-api-649875cf66-lf4w9
```

**Comment by TBBle** [comment]
If you check the logs for kube-proxy, there may be [a log message when picking an endpoint](https://github.com/kubernetes/kubernetes/blob/v1.20.9/pkg/proxy/winuserspace/roundrobin.go#L138), and then either one [when using the existing affinity](https://github.com/kubernetes/kubernetes/blob/v1.20.9/pkg/proxy/winuserspace/roundrobin.go#L156), or one [when no existing affinity was seen, so it stores a new one](https://github.com/kubernetes/kubernetes/blob/v1.20.9/pkg/proxy/winuserspace/roundrobin.go#L175). It's possible those logs are not included by default, and I'm not sure how to turn up the log-level in kube-proxy.

That said, with `externalTrafficPolicy: Local`, on a `type: LoadBalancer`, I wouldn't expect session affinity to work across multiple nodes generally, as the LoadBalancer is picking the node to send to, and the traffic policy then doesn't allow that node to choose a pod on another node. (That's not the problem here, as both pods are on the same node)

I don't know how the AKS LoadBalancer implementation works, but is it possible that its support for `externalTrafficPolicy: Local` doesn't go via kube-proxy, but directly to the Pod? I know AWS's current LoadBalancer implementation can do that, and I think GCE's does too? It looks to me like [this isn't yet supported for Azure though](https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#configure-load-balancer-backend).

I would suggest repeating your test but talking to the `nodePort` port on your worker node rather than the load balancer IP/port, and see if the problem still exists, in order to rule out any LoadBalancer interactions. Perhaps even make it a NodePort Service to be absolutely sure.

Also, it might be better raise this question with the Kubernetes project, since that's where the relevant code lives.
