### ISSUE TITLE
Problem to build docker image with window server core 2022 docker file

### ISSUE THREAD

**Issue by rarajabs** [microsoft/Windows-Containers#198]
Hi,

I have issue to build docker image

I download docker file for windows server core 2022 with dotnet sdk 5.0 from docker hub: https://github.com/dotnet/dotnet-docker/blob/09021f8b411d66086db31a538da1e9a185d3ed44/src/sdk/5.0/windowsservercore-ltsc2022/amd64/Dockerfile

After that I was trying to build it from docker file. But I get error as screenshot below: 
![image](https://user-images.githubusercontent.com/1460421/150501080-863efbaa-0bfd-4058-9e69-84b28006dcf7.png)

**Comment by cwilhit** [comment]
@rarajabs are you still experiencing this issue?

**Comment by michbern-ms** [comment]
I did run this Dockerfile locally with docker 20.10.7 and was successful.

```
Run 'dotnet [command] --help' for more information on a command.
Removing intermediate container 754a5389bdcb
 ---> e79ede408068
Successfully built e79ede408068
```

**Comment by rarajabs** [comment]
I am still having the same issue. it is because my local system is missing sdk?

![image](https://user-images.githubusercontent.com/1460421/155071790-20ba7daa-d71f-432e-8b8a-3f5b3c95afdf.png)

**Comment by cwilhit** [comment]
@rarajabs can you please confirm:

- you are running on Windows 10
- what version of Docker are you using?

**Comment by rarajabs** [comment]
1. Windows 10
2. Docker version 20.10.12

**Comment by cwilhit** [comment]
I was able to repro this. It is due to the Docker daemon being set to Linux containers rather than Windows containers. Switching to Windows containers ([docker docs explaining how to do this](https://docs.docker.com/desktop/windows/#switch-between-windows-and-linux-containers)) and then running a clean rebuild should resolve the issue for you.

One thing to note is, since you're running on a Windows 10 21H1 machine, the docker build process would fail (since you're trying to build a container based on a newer OS version). To get around this, you could change the build instruction to use a Server Core image that that matches your container host.

**Comment by rarajabs** [comment]
Thank you for your explanation. 

I didn't noticed there is a different OS type on Docker daemon in windows machine.

I am closing this question since this is not related the docker file.
