### ISSUE TITLE
Windows Firewall Security Policy preventing network connectivity in Hyper-V guests and Windows containers with Hyper-V "internal" virtual switches

### ISSUE THREAD

**Issue by JustinChristensen** [microsoft/Windows-Containers#203]
I've been trying to track down why I can't establish network connectivity using the default NAT network when in Windows containers mode on my domain-joined corporate workstation for a while now. I think I've figured it out, and I was hoping that Microsoft may be able to provide some guidance on what the expected behavior should be for the interaction between Security Policy, Windows Firewall, the Host Networking Service, Internet Connection Sharing, and Hyper-V's virtual switches. 

This impacts both Docker for Windows and Hyper-V generally. 

Specifically what is happening is that when the Security Policy "Apply Local Firewall Rules" is set to "No" in the public profile, local firewall rules that Internet Connection Sharing and the Host Networking Service adds to permit DHCP and DNS for Hyper-V guests are no longer applied. This means that attempts to broadcast for DHCP and DNS queries in the guest Hyper-V VM (or container) are then blocked by Windows Firewall. 

I've tested this in isolation on a Windows 10 Pro VM in Azure, with only this specific Security Policy configured through the Local Security Policy snap-in.

I've got a gist where I've been tracking my notes on this [here](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49). I've used netsh to capture the network events that prove that this is the case, and you can see what filters are making the allow/deny decisions with these files:

Apply Local Firewall Rules: Yes
[DHCP Broadcast Allow](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dhcp-allow-txt)
[DNS Allow](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dns-allow-txt)

Apply Local Firewall Rules: No
[DHCP Broadcast Deny](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dhcp-deny-txt)
[DNS Deny](https://gist.github.com/JustinChristensen/77b1496331a59940342c577233046a49#file-netevent-dns-deny-txt)

You can see from this that when this security policy is either not configured or set to Yes, that the local rules that the Host Networking Service and ICS add permit the traffic. 

Now, in corporate environments administrators are typically wont to set this Security Policy to No, and then to configure and maintain a list of static inbound firewall rules that get distributed to workstations via policy updates. What I'm wondering from Microsoft is:
1. Are these local rules that ICS and the Host Networking Service adds to support Hyper-V networking supposed to be clobbered by this security policy? Or should they be a special case? That is, is it by design that that security policy prevents these Windows services from doing what they need to do to support Hyper-V networking?
2. If that is working as intended, what would be the right way to configure security policy to allow these services to apply their local firewall rules? From what I see, those rules are dependent on local system state like security identifiers and interface identifiers, (which allows them to be more narrowly scoped), and so maintaining another static firewall rule in the list wouldn't necessarily be an effective solution. Should there be another security policy callout somewhere that says something like "Disallow local firewall rules, except for those added by Windows Services X, Y, and Z"?
3. Is there documentation out there somewhere that details how this interaction between Hyper-V, Windows Firewall, HNS, ICS, and this Security policy is supposed to work that I just missed in my search?

**Comment by dcantah** [comment]
@microsoft/containernet-msft

**Comment by houha2** [comment]
1. Are these local rules that ICS and the Host Networking Service adds to support Hyper-V networking supposed to be clobbered by this security policy? Or should they be a special case? That is, is it by design that that security policy prevents these Windows services from doing what they need to do to support Hyper-V networking?

Yes, these local rules are getting clobbered by this security policy and is by design to allow Enterprise managed devices more security protections.

2. If that is working as intended, what would be the right way to configure security policy to allow these services to apply their local firewall rules? From what I see, those rules are dependent on local system state like security identifiers and interface identifiers, (which allows them to be more narrowly scoped), and so maintaining another static firewall rule in the list wouldn't necessarily be an effective solution. Should there be another security policy callout somewhere that says something like "Disallow local firewall rules, except for those added by Windows Services X, Y, and Z"?

The right way would be to set the security policy “Apply Local Firewall Rules” to “Yes” which is the default setting for the policy. 

3. Is there documentation out there somewhere that details how this interaction between Hyper-V, Windows Firewall, HNS, ICS, and this Security policy is supposed to work that I just missed in my search?

We do have documentation on the [security policy here](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/planning-settings-for-a-basic-firewall-policy), but it does not detail the interaction between Hyper-V, HNS, ICS, and Firewall. There are plans to get this documented as you are not the only person facing this issue.

**Comment by JustinChristensen** [comment]
Hey @houha2 

I appreciate the reply! 

It's encouraging to hear that this is all on your radar. 

One slight clarification: Are there discussions of adding a security policy callout that allows those local firewall rules for just those Windows services to continue applying, even if the administrator continues to want to disable users from managing their own firewall rules locally?

I could see there being some administrators in certain kinds of environments having heartburn about allowing a workstation user blanket permission to administer their own firewall rules at the perimeter. It seems like this Hyper-V/Docker machinery is a special case that an administrator would want the capability to enable while still preventing the user from generally managing firewall rules locally. 

Again, thanks for the response.

**Comment by cwilhit** [comment]
_>Are there discussions of adding a security policy callout that allows..._
Spoke with @houha2 offline and it does not sound like there's anything in plan right now for this.

**Comment by JustinChristensen** [comment]
> _>Are there discussions of adding a security policy callout that allows..._ Spoke with @houha2 offline and it does not sound like there's anything in plan right now for this.

Ah. I'll be honest and say that I was hoping for a bit more insight into the considerations involved there, but I suppose beggars can't be choosers on forums such as these. That said, it sounds like the U.S. government has been sending out security advice that contradicts the recommendation that was given above, and so that leaves things a bit confusing. 

I guess I'll just have to wait for the extra documentation @houha2 mentioned was forthcoming. Thanks again.

**Comment by cwilhit** [comment]
No problem, happy to help. Closing this issue.

**Comment by arencambre** [comment]
Did the documentation referenced in https://github.com/microsoft/Windows-Containers/issues/203#issuecomment-1057341968 get produced? I can't find it.

I am running into the same problem. While I got an exception to allow me to set exceptions for my public network profile, I am not sure what exceptions to set to permit my VMs to use the network.

**Comment by kelstra** [comment]
Like @JustinChristensen, I ran into this issue with a Hyper-V Debian 13 Guest and the Default Switch.

I have a restrictive firewall setup that blocks both inbound and outbound connections that do not match a rule.

Additionally, the Security Policy "Apply Local Firewall Rules" is set to "No" because Microsoft seems to think that Solitaire and friends need to open gaping holes in the firewall, and Windows creates very permissive inbound and outbound rules for them without my consent. But I digress.

The Event Viewer Security log provided vital clues.

I tackled DHCP first.

1. Create a firewall inbound rule with the following parameters:

a) General tab

`Name = Hyper-V DHCP Discover`

b) Programs and Services tab

`This program = %SystemRoot%\System32\svchost.exe`

c) Protocols and Ports tab

```
Protocol type = UDP
Local port = Specific Ports = 67
Remote port = Specific Ports = 68
```

d) Scope tab

```
Local IP Address = These IP addresses = 255.255.255.255
Remote IP Address = These IP addresses = 0.0.0.0
```

2. Create a firewall outbound rule with the following parameters:

a) General tab

`Name = Hyper-V DHCP Offer`

b) Programs and Services tab

`This program = %SystemRoot%\System32\svchost.exe`

c) Protocols and Ports tab

```
Protocol type = UDP
Local port = Specific Ports = 67
Remote port = Specific Ports = 68
```

d) Scope tab

```
Local IP Address = These IP addresses = 172.16.0.0/12
Remote IP Address = These IP addresses = 172.16.0.0/12
```

I already had a predefined Core Networking - Dynamic Host Configuration Protocol (DHCP-Out) outbound rule for my host's internet connectivity. Probably not relevant, but worth a mention.

DNS was puzzling.

My VM guest's /etc/resolv.conf file contained one nameserver entry:

`nameserver 172.31.64.1`

The host firewall log showed a blocked inbound connection from the VM guest to the Default Switch (172.31.69.147 to 172.31.64.1:53).

So, I created an inbound firewall rule to allow such DNS queries.

I already had a predefined Core Networking - DNS (UDP-Out) outbound rule for my host's internet connectivity. However, DNS was still not working in the VM guest, and the Event Viewer Security log now showed blocked outbound connections from the host to the router (192.168.0.30 to 192.168.0.1:53), and from the host to Google Public DNS (192.168.0.30 to 8.8.8.8:53).

I found this quite odd, as the aforementioned outbound DNS rule should allow the queries. DNS queries work just fine on the host.

I am not sure how Hyper-V's Default Switch's internet connectivity works behind the scenes, but it looks like the guest directs DNS queries to the Default Switch, which in turn forwards them to the host, which in turn performs a normal DNS query. I could be totally wrong, but it seems as if the host firewall somehow knows that these queries did not originate on the host's subnet and thus blocks them.

I tried a different approach, modifying my VM guest's /etc/resolv.conf file. I replaced the existing nameserver entry with two entries (Google's and Cloudflare's):

```
nameserver 8.8.8.8
nameserver 1.1.1.1

```
DNS queries from the VM guest now worked.

I deleted the earlier inbound firewall rule that allowed guest to Default Switch DNS queries, as external servers are now queried directly.

@franklesniak and I posted answers here:

[Why doesn’t Hyper-V’s default switch provide IP address?](https://superuser.com/questions/1741993/why-doesn-t-hyper-v-s-default-switch-provide-ip-address)
