### ISSUE TITLE
Error when using --mount option with docker Windows container

### ISSUE THREAD

**Issue by patrikjx64** [microsoft/Windows-Containers#206]
**Describe the bug**
Using the --mount argument when starting a Windows container results in a crash. It does not
seem to which argument is passed since even using --mount with no arguments gives
the same result:
![image](https://user-images.githubusercontent.com/100402246/155666529-d346ddd2-2a42-4980-9633-b04557da65b6.png)

**To Reproduce**
Start a Windows based container with the --mount argument. I am using 
Docker for Windows . I am using the following command, do note that the
given arguments to --mount do not seem to matter:
`docker run mcr.microsoft.com/windows/server:ltsc2022-KB5010354-amd64 --mount`

**Expected behavior**
I would expect an error, but not a crash, when using --mount with no arguments. I would
expect the given directory to be mounted if the proper arguments where given 
(source,target,rw etc). 

**Configuration:**
I can reproduce the issue on Windows 11 Business 21H2 and Windows 10 Business 21H1,
using Docker for Windows 4.5.1 (74721). The issue seesms to affect every recent container
image of Windows, Windows Server, and Windows Server Core. 

**Additional context**
The issue is very easy to reproduce, as you can see in my example. I need this feature in
my work so a fix or a workaround would be appreciated.

**Comment by cwilhit** [comment]
Hey @patrikjx64 are you sure you have the semantics right? If you look at the Docker [documentation ](https://docs.docker.com/engine/reference/commandline/run/)you'll see this usage:

`docker run [OPTIONS] IMAGE [COMMAND] [ARG...]`

You have the `--mount` option coming _after_ the image, so it's getting interpreted as the process to be executed in the image, and it's returning an error because no such .exe exists. If you affix the `--mount` option before the image, you should see it give a proper error that a key/value pair needs to be specified for the mount command.

![image](https://user-images.githubusercontent.com/5685031/155768324-5e256f03-81b7-41af-97e8-23cfffa0edcb.png)

If this was working before, it sounds like an issue more for the docker repo (moby/moby).

**Comment by patrikjx64** [comment]
Hi @cwilhit ,

It would seem you are correct. Changing the order of the arguments did, in fact, work. I wish the error information was a bit more clear on what is going on, but at least I can get back to work now. Thank you!
