### ISSUE TITLE
Is Sysmon compatible with a Windows Docker container?

### ISSUE THREAD

**Issue by jt0dd** [microsoft/Windows-Containers#220]
Building security test labs in Docker isn't new, but it's only been done to simulate Linux environments previously, with any Windows hosts requiring some technology (like Vagrant) to glue Windows VMs into the Docker environment: https://github.com/SecurityWeekly/vulhub-lab

We've been experimenting with using Docker for a security testing lab because Docker containers are far easier to configure, resource efficient, and more easily automatable than VMs. Our first down-fall was that Active Directory is disabled in Windows Docker server images. 

Question1: Is there some technical limitation in the way of that ever being enabled in the future? It would be great to have a fully Docker run security testing lab.

In the mean time, we'll bypass that issue. We can use Vagrant with VMs to add a DC to our environment later. But at least we can enjoy the benefits of Docker for our other Windows hosts, right? We tested a single Windows Docker Host, tried installing Sysmon, and got errors:

```
docker-compose up --build -d
Building win10
Sending build context to Docker daemon   87.5MB
Step 1/6 : FROM mcr.microsoft.com/windows:20H2
 ---> e26601ac60e0
Step 2/6 : COPY ["./Winlogbeat", "C:/Program Files/Winlogbeat/"]
 ---> Using cache
 ---> 95b0887fb4c2
Step 3/6 : COPY ["./Sysmon", "C:/Program Files/Sysmon/"]
 ---> Using cache
 ---> 39b124c3b18a
Step 4/6 : RUN ["C:/Program Files/Sysmon/Sysmon.exe", "-i", "-accepteula", "-l", "-n"]
 ---> Running in d5632a309cd3


System Monitor v13.33 - System activity monitor
By Mark Russinovich and Thomas Garnier
Copyright (C) 2014-2022 Microsoft Corporation
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.
Sysinternals - www.sysinternals.com

Sysmon installed.
SysmonDrv installed.
Starting SysmonDrv.
SysmonDrv failed to start.
Failed to start the driver:
This operation returned because the timeout period expired.

Stopping the service failed:
The service has not been started.
SysmonDrv removed.
Stopping the service failed:
The service has not been started.
Sysmon removed.
The command 'C:/Program Files/Sysmon/Sysmon.exe -i -accepteula -l -n' returned a non-zero code: 1460
ERROR: Service 'win10' failed to build : Build failed
```

Our Dockerfile looks like this:

```
FROM mcr.microsoft.com/windows:20H2

COPY ["./Winlogbeat", "C:/Program Files/Winlogbeat/"]
COPY ["./Sysmon", "C:/Program Files/Sysmon/"]

RUN ["C:/Program Files/Sysmon/Sysmon.exe", "-i", "-accepteula", "-l", "-n"]
#RUN ["C:/Program Files/Winlogbeat/install-service-winlogbeat.ps1"]
#RUN ["Start-Service", "winlogbeat"]
```
So now we're wondering if the features Sysmon relies on may not be present in a Docker environment, and our use-case for Docker is non-viable.

Question 2: Is there any workaround?

**Comment by cwilhit** [comment]
Hi @jt0dd, regarding the questions about active directory and Windows containers, are you asking whether you can enable the Active Directory Domain Controller feature in a Windows container, or something else? If you are asking about using an AD identity in the container, we do support using [AD domain identities via gMSA ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts); you cannot domain join a Windows container.

To your second question about sysmon: due to the isolated nature of containers & that they share the underlying host kernel, we disallow certain operations from within containers such as installing device drivers on the host. I see in sysmon description, "System Monitor (Sysmon) is a Windows system service and **device driver** that...". I suspect it's failing for this reason. 

As for any workarounds, we recently released support a new container type called "HostProcess containers" (mentioned in Microsoft blog [here](https://techcommunity.microsoft.com/t5/containers/what-s-new-for-windows-containers-on-windows-server-2022/ba-p/2167036)) to address this use case, albeit for the purposes of Kubernetes ([docs](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/#when-should-i-use-a-windows-hostprocess-container)) and it's not something that is supported through Docker CLI right now.

**Comment by jt0dd** [comment]
> you cannot domain join a Windows container.

Yes, I know I can't. I'm wondering why. I suspect it's because Microsoft doesn't want to offer the full functionality of their windows server OS freely on Docker (Active Directory being a major feature), but as a result those of us in the security community will never be able to leverage the strengths of Docker toward simulating a realistic AD network. Right now this is extremely non-trivial, and [projects which attempt it](https://github.com/clong/DetectionLab/issues?q=is%3Aissue+is%3Aclosed) (aside from lacking Docker's memory efficiency benefits from the kernel re-use) suffer from a very high rate of things breaking.

That said, even if AD weren't disabled, Sysmon is so prevalent as a security logging tool across the industry, that it not being supported would in itself be a deal-breaker. That sounds like an issue Microsoft couldn't trivially enable a feature to solve. As noted, that kernel sharing thing and Sysmon using a driver sounds like a problem.

**Comment by jt0dd** [comment]
But it would be an incredible gift to the cyber security community if these things could be figured out. There's no shortage of pros in this community [wanting to use Docker in this way](https://www.youtube.com/watch?v=xSO4UEx4NUA). It's doable on Linux, just remains out of reach for simulating Windows / AD. That said, I realize with the Sysmon issue, it becomes more of a technology problem than a licensing consideration. Even so, I think it's at least worth posing the feature request to the Microsoft (and Docker) teams.

Microsoft would need to enable Active Directory. Docker would need to introduce some way for Windows containers to support Sysmon. One of these things things seems difficult, neither of them seems impossible. The upside for the cybersec community would be massive. What's the value proposition? Well it's long-term, but both Docker and Microsoft benefit from more people being familiar and skilled with configuring and securing Active Directory environments. This feature would lower the barrier to entry for getting familiar with what it's like to navigate and secure an AD environment. High school students could be doing it from their gaming PCs with just a single command thanks to Docker.

**Comment by jt0dd** [comment]
@cwilhit could you add the feature-request tag?

**Comment by cwilhit** [comment]
Hey @jt0dd, since the Windows platform now supports HostProcess containers, that would address the limitation around installing sysmon to a container host (whether sysmon would then run correctly in a container is another story--maybe sysmon would require some changes in its codebase to be container-aware). That HostProcess containers are not yet exposed through Docker CLI would be up to the Docker to go and plumb, though.

On the topic of not being able to domain join a container, thank you for sharing your feedback & scenario, however domain membership is not planned to be supported. Windows containers have certain attributes that make them unsuitable for AD domain join (they're ephemeral, they come and go, customers tend to run many of these things on a given machine, pushing group policy to them would be time consuming and impact the time it takes to specialize them thereby impacting launch times, etc). 

Rather than keep this around as a feature request I am going to close this out. If our stance on this changes or we get additional data points from others in the community, we can always reopen this issue at a later date.
