### ISSUE TITLE
install-containerd-runtime.ps1 add missing SYMLINKD steps

### ISSUE THREAD

**Issue by kkbruce** [microsoft/Windows-Containers#245]
**Describe the bug**

install-containerd-runtime.ps1 missing SYMLINKD steps ( https://github.com/microsoft/windows-container-networking/issues/70#issuecomment-1185231433 ), without `c:\etc\cni\net.d` and `c:\opt\cni\bin` of settings, `--cni` will not work.

**To Reproduce**

see: https://github.com/microsoft/windows-container-networking/issues/70

**Expected behavior**

Run with `--cni` and container get the IP address:

```
ctr run --cni --rm mcr.microsoft.com/windows/nanoserver:ltsc2022 test ipconfig
```

**Configuration:**
 - Edition: **Windows Server 2022**
- Base Image being used: **mcr.microsoft.com/windows/nanoserver:ltsc2022**
 - Container engine: **containerd**
 - Container Engine version: **v1.6.6**

**Additional context**

Refer another containerd-installer [reateCtrSymlinks](https://github.com/lippertmarkus/containerd-installer/blob/1185b1ba2423682f18159ce1addf8d0acd49b111/cmd/containerd-installer/install/cni.go#L65) code.

**Comment by lippertmarkus** [comment]
Copying my answer from your other issue: 

The symlink setup is only needed for ctr to work, but isn't required for others like crictl or kubelet and that's why that isn't part of the runtime setup script. ctr paths have been changed in https://github.com/containerd/go-cni/pull/103/files#diff-df2b994645f533d6ced46ef610f95cfc41a3cecc099a873a9b47fadccb605b9b
