### ISSUE TITLE
Windows Server 2022 container on Windows 10 (10.0.19044) host.

### ISSUE THREAD

**Issue by amaltinsky** [microsoft/Windows-Containers#258]
According to the [documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1), it should be possible to run Windows Server 2022 on Win10 21H1:

![image](https://user-images.githubusercontent.com/103459440/183480939-8749364c-a44a-47c7-a4d9-55231a7a928d.png)

However, in practice it doesn't seem to work:

```
PS C:\Windows\system32> docker run --rm --isolation=hyperv mcr.microsoft.com/windows/server:ltsc2022
Unable to find image 'mcr.microsoft.com/windows/server:ltsc2022' locally
ltsc2022: Pulling from windows/server
docker: no matching manifest for windows/amd64 10.0.19044 in the manifest list entries.
See 'docker run --help'.
```

Is this a bug or a documentation issue?

**Comment by amaltinsky** [comment]
Relevant issue from approx. a year ago: #155

**Comment by gusarov** [comment]
+1 have the same issue here...

**Comment by maltalex** [comment]
It does work with `mcr.microsoft.com/windows/server:win10-21h1-preview`, but it's more than a year old.

**Comment by mloskot** [comment]
Same issue, with the difference that Windows 10.0.19044 is now 21H2 and not 21H1 - no, it is not Windows 11, it's still 10:

![image](https://user-images.githubusercontent.com/80741/186897159-01034807-5ac4-4aef-9b9f-376e62524f26.png)


```
> docker run mcr.microsoft.com/windows/nanoserver:ltsc2022
Unable to find image 'mcr.microsoft.com/windows/nanoserver:ltsc2022' locally
ltsc2022: Pulling from windows/nanoserver
docker: no matching manifest for windows/amd64 10.0.19044 in the manifest list entries.
```

```
> docker run mcr.microsoft.com/windows/servercore:ltsc2022
Unable to find image 'mcr.microsoft.com/windows/servercore:ltsc2022' locally
ltsc2022: Pulling from windows/servercore
docker: no matching manifest for windows/amd64 10.0.19044 in the manifest list entries.
```

**Comment by amaltinsky** [comment]
After not getting a response here we ended up contacting Microsoft Support. I'll spare everyone the details of the almost month-long correspondence, but the end result is that running Windows Server 2022 images on Windows 10 is simply not supported (anymore) by Microsoft.

When Windows Server 2022 was released, there were a few specific images for _temporarily_ running Win Server 2022 on Windows 10. But they've been discontinued and Microsoft expects customers to switch to Windows 11 or Windows Server 2022 as a host.

In all likelihood, this isn't due to a technical limitation.

**Comment by vrapolinario** [comment]
On behalf of the Windows containers team I apologize for the lack of clarity on this article and the delay to fix it. This information on the doc page referenced is incorrect. We did enable WS2022 images to be available on Win10 for a short period (as noted by @amaltinsky) but we said that would be temporary since the beginning. You can check the blog post here: https://techcommunity.microsoft.com/t5/containers/windows-server-2022-and-beyond-for-containers/ba-p/2712487.

I made changes to the page and have already signed off on the commit. This will be published on the docs page soon. The revised page will better show the information about version compatibility for host and container images.

Also, to clarify on the limitation: Windows Server 2022 has a newer build version compared to Windows 10. This means we would have to validate scenarios of forward compatibility between host and container image (which requires additional internal testing), to ensure customers won't see any broken scenarios, so this is a technical limitation. We are investigating internally if this is feasible or not and feedback like this helps us make the case. No commitment or timeline on this at this point.

**Comment by amaltinsky** [comment]
@vrapolinario Thank your for the reply and the proposed documentation change.

I'd like to point out that the current confusion about host/guest compatibility both now and especially going forward presents a significant risk for companies considering Windows Containers for mission-critical applications. One of the biggest advantages containers offer is having a **consistent** environment between development and production. So being able to build, run, and debug containers locally on a developer's machine is a big part of the appeal. 

Generally speaking, developers don't tend to run Windows Server on their boxes. And moving all developers to Windows 11 is a significant undertaking that takes time to pull off (and can also fail due to difficulties with porting legacy software and build tools to the new platform). Also, what if tomorrow Microsoft releases Windows Server 2024 that requires Windows 12 or something of that nature? Or what if Windows 11 support suddenly vanishes the same way that Windows 10 support did? There are a lot of unknowns here for potential adopters.

Regarding the nature of the limitation, could you expand on that? If Windows 10 is capable of leveraging hyper-v to run Linux containers which are completely foreign to it, why does a newer version of Windows pose a challenge?

**Comment by vrapolinario** [comment]
Thanks for the additional information. It surely helps us in thinking how to prioritize this.

On your comment about support, please note that Microsoft has clear statements on support for Windows and Windows Server, including Windows containers. Windows 10 can run Windows Server 2019 images. The issue here it the handle of newer images, which is the feedback we're taking and looking into.

On the limitation on why this is: 
- First, not to confuse anyone else coming to this thread, Linux containers on Windows (LCOW) was an experimental feature that is not supported anymore. You can run Linux containers on WSL 2, which has its own utility VM. Linux containers on WSL 2 is not the same as LCOW.
- The thing about the scenario is the support and experience we want customers to have. If we enable something like this, we need to ensure that this is not a scenario that is breaking. Each new scenario = new testing that we need to perform internally and this scenario is not currently covered because we never supported newer images on older hosts. On the other hand we never had a situation such as Windows 10 and 11 were in market at the same time. Because of that we are looking at this internally.

Hopefully this helps - I'll update this thread once I have more to share. By the way, the documentation has been updated to reflect the correct support statements.

**Comment by cdaf** [comment]
Before I go though the trauma, am I correct that Windows Server 2022 is supported on Windows 11 via docker-desktop, or is the a whole new ecosystem in Windows 11?

**Comment by maltalex** [comment]
If I understand correctly, Windows Server 2022 should be supported on Windows 11 using docker-desktop. Though, only with hyper-v isolation, not process-isolation. Haven't tried it myself, though.

**Comment by cdaf** [comment]
Thanks, I guess there's only one way to find out ...

**Comment by cdaf** [comment]
I can now confirm that Windows Server 2022 is supported in Windows 11.

Note: There are two base images available mcr.microsoft.com/windows/servercore:ltsc2022 and mcr.microsoft.com/windows/server:ltsc2022. I don't know the differences between the two, with the only difference in the _about this image_ section being the latter image having the caveat "It is only available with Windows Server 2022 release". Neither image configuration section have updated the required host OS from _Windows 10_ to _Windows 11_.

**Comment by Juarezhm** [comment]
Closing this issue since documentation has been updated

**Comment by kjherdez** [comment]
To be clear windows Server are not the only base images. There's also just a plain windows base image that pulls for me on Win 10 pro. I didn't realize this because google searches seem to mostly return info on the win server images.

**Comment by amaltinsky** [comment]
> Thanks for the additional information. It surely helps us in thinking how to prioritize this.
> 
> On your comment about support, please note that Microsoft has clear statements on support for Windows and Windows Server, including Windows containers. Windows 10 can run Windows Server 2019 images. The issue here it the handle of newer images, which is the feedback we're taking and looking into.
> 
> On the limitation on why this is:
> 
>     * First, not to confuse anyone else coming to this thread, Linux containers on Windows (LCOW) was an experimental feature that is not supported anymore. You can run Linux containers on WSL 2, which has its own utility VM. Linux containers on WSL 2 is not the same as LCOW.
> 
>     * The thing about the scenario is the support and experience we want customers to have. If we enable something like this, we need to ensure that this is not a scenario that is breaking. Each new scenario = new testing that we need to perform internally and this scenario is not currently covered because we never supported newer images on older hosts. On the other hand we never had a situation such as Windows 10 and 11 were in market at the same time. Because of that we are looking at this internally.
> 
> 
> Hopefully this helps - I'll update this thread once I have more to share. By the way, the documentation has been updated to reflect the correct support statements.

@vrapolinario Sorry for bringing up this issue again, but I was wondering whether there are any updates about the Windows Host <-> Guest compatibility going forward? I work for a large company which sells a Windows-based product, and we're staying away from Docker and Windows containers mostly because of the compatibility concerns I outlined previously.

**Comment by vrapolinario** [comment]
As of today, we haven't had any updates on this. Tagging @ntrappe-msft.
I wanted to point out that while we don't have news on this front, the team has listened to this feedback about version compatibility over the years. Windows Server Annual Channel for containers introduces portability, which while doesn't address this particular scenario, it's a step in the right direction. I'll let Nicole add anything here (if there's anything to be added).
