### ISSUE TITLE
Missing T2Embed.dll in Windows Server Core 2019 LTSC image. Export to PDF from ASP.NET RDLC report app fails.

### ISSUE THREAD

**Issue by tanukus** [microsoft/Windows-Containers#266]
**Describe the bug**
We are getting an error "System.DllNotFoundException: Unable to load DLL 'T2Embed'" in our ASP.NET 4.8 web application running in a container. The app uses Microsoft.Report.Viewer to extract a PDF from a RDLC report, that is when this error occurs.

This DLL is found in host VM, however the container file system is missing the T2Embed.dll. 

Copying this DLL in the Docker file with COPY from host VM seems to resolve the issue. Is this a viable workaround (licensing etc)?
If not how can this dll be obtained? 

**To Reproduce**

**Expected behavior**
Export to PDF successful. 

**Configuration:**
 - Edition: [Host VM: Windows Server Core 2019 Data Center]
- Base Image being used: [mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019]
 - Container engine: [docker]
 - Container Engine version [20.10.9, build 591094d]

**Additional context**

**Comment by michbern-ms** [comment]
@tanukus While we investigate ... I did find this issue which had similar symptoms and a possible workaround.  I am not recommending the workaround, just noting it.  https://github.com/Microsoft/nav-docker/issues/145

**Comment by tanukus** [comment]
@michbern-ms: Yes, it did work for me as I stated above.

> Copying this DLL in the Docker file with COPY from host VM seems to resolve the issue. Is this a viable workaround (licensing etc)?

**Comment by michbern-ms** [comment]
Thanks, @tanukus.   Here's what I found:

- The t2embed.dll is excluded from Server Core by design.  It is rather part of the App Compatibility FoD for ServerCore.  (https://docs.microsoft.com/en-us/windows-server/get-started/server-core-app-compatibility-feature-on-demand)  
- Microsoft cannot recommend or support copying libraries from one OS to another; it is not consistent with our license agreements.   If a future version of the library added a dependency on some other library, your container would not have the second library and it would break.
- For a Windows Containers workflow, rather than trying to install the App Compat FoD, it would be simpler and more efficient to use the Windows Server image (https://hub.docker.com/_/microsoft-windows-server/)

We recognize that it would be attractive to be able to use Server Core plus a package containing t2embed.dll, and we are considering that feature for a future release.

Thanks,
Michael

**Comment by tanukus** [comment]
@michbern-ms, thanks. There seems to be no 2019 version for Windows Server image. Does that mean we need to use full Windows image as base and build a custom image for ASP.NET 4.8 runtime? That wouldn't be ideal and would impact a lot of our current work.

>>"We recognize that it would be attractive to be able to use Server Core plus a package containing t2embed.dll, and we are considering that feature for a future release."

Is there a time line?

**Comment by mthalman** [comment]
> There seems to be no 2019 version for Windows Server image. Does that mean we need to use full Windows image as base and build a custom image for ASP.NET 4.8 runtime?

That's correct. Container images for .NET Framework are only available on Windows Server Core. There are currently no plans to provide .NET Framework images based on the full Windows Server. There just isn't enough demand for them to justify the cost associated with producing them.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
, please provide an update or close this issue.

**Comment by fady-azmy-msft** [comment]
Closing this issue because we don't have current plans to provide .NET Framework images on full Windows Server.

**Comment by GhayourAli** [comment]
@michbern-ms  Any update on getting t2embed.dll in available in windowsservercore? I am trying to generate a pdf file using .net 7.0 app, but it fails because this dll is not available. Any solution for this problem?

**Comment by michbern-ms** [comment]
@GhayourAli No, no update to report.  It is still under consideration.  Our suggestion is to use the Windows Server image (https://hub.docker.com/_/microsoft-windows-server/) which does include that DLL.
