### ISSUE TITLE
Dropped connections from swarm overlay network on Server 2019

### ISSUE THREAD

**Issue by dmduggan** [microsoft/Windows-Containers#269]
**Describe the bug**
After upgrading from Server 2016/Docker 18.09.14 to Server 2019/Docker 20.10.9 we started experiencing dropped connections to our Oracle database.

To reproduce I wrote a small .NET Framework application that opens a connection, makes a query, sleeps for 7 minutes and then tries to make another query. Running the same image on the default "nat" network does not exhibit this behavior.

**To Reproduce**
1. docker stack deploy -c stack.yml

``` stack.yml
version: "3.8"

services:
  odac:
    image: testodac:latest
```

2. Monitor logs for dropped connection.
`Oracle.DataAccess.Client.OracleException (0x80004005): ORA-03135: connection lost contact`

**Expected behavior**
Service not to lose connection.

**Configuration:**
 - Edition: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.3287)
 - Base Image being used: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
 - Container engine: docker (Mirantis)
 - Container Engine version: 20.10.9

**Additional context**

**docker version**

```bash
Client: Mirantis Container Runtime
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.12m2
 Git commit:        591094d
 Built:             12/21/2021 21:34:30
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.16.12m2
  Git commit:       9b96ce992b
  Built:            12/21/2021 21:33:06
  OS/Arch:          windows/amd64
  Experimental:     false
```

**docker info**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.9
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: icbod14si9nowc2q0noek60el
  Is Manager: true
  ClusterID: t7tix610jmx0a6vau5kys3lxi
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.135.28.243
  Manager Addresses:
   10.135.28.243:2377
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.3287)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 8GiB
 Name: EC2AMAZ-5HKAR00
 ID: 6VW2:47K4:XZRJ:6S4L:UZHQ:MIIC:J5MJ:MWG5:FOWZ:NR6T:7MF6:IMNX
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by fady-azmy-msft** [comment]
Thank you for bringing this to our attention, I've created an internal ticket to track this (#41230831) and someone will follow up on this.

**Comment by dmduggan** [comment]
I also reproduced this on Window Server 2022. So works on Server 2016, fails on Server 2019 and Server 2022.

**Comment by corhere** [comment]
On Windows Server 2019 and above, the Host Networking Service (HNS) sets up overlay networks which use Virtual Filtering Platform rules for NAT to/from external services. HNS on Windows Server 2016 leverages WinNAT for external service access from overlay networks. The default `nat` network uses WinNAT on all versions of Windows. Given that the issue can be reproduced on Windows Server 2019 and 2022 with containers attached to an overlay network but not the `nat` network, nor on Windows Server 2016 with either network type, VFP NAT appears to be a necessary condition to reproduce the issue. I have learned by poking around with `vfpctrl.exe` that the VFP `OutBoundNAT` rules created by HNS for container overlay networks are configured with a Flow TTL of 240 seconds. I have not been able to confirm on my test system (`Get-NetNat` returns an empty collection despite `Get-NetNatExternalAddress` returning four objects), but from what I can infer from web searches the `TcpEstablishedConnectionTimeout` on WinNAT networks defaults to 1800 seconds. I suspect that this difference in configuration is the root cause of the reported issue.

Is it possible to configure the NAT connection timeout parameter with the Host Compute Network API? I didn't see anything in the JSON schema. If not, could such an option be added to the API? Having significant differences in how the container NAT behaves on overlay networks (Swarm services) compared to the default `nat` network (basic containers) is surprising to Docker users, as demonstrated by this ticket. Being able to dictate the NAT configuration through the HCN API would allow us to smooth over the differences in system defaults from the Moby side.

**Comment by fady-azmy-msft** [comment]
Hey @dmduggan I spoke with my team about this issue and we aren't prioritizing Docker / Docker Swarm related bugs as we focus on containerd / K8s.
