### ISSUE TITLE
How can I change the size of pagefile.sys?

### ISSUE THREAD

**Issue by chaotive** [microsoft/Windows-Containers#271]
I have some applications that because of legacy issues, they fail if they don't have enough page file memory available. I have not been able to increase the page file size on my servercore container, because I can't do reboot after running the command line parameters required to make it work.

For reference, these are the commands I run, but they require a reboot after using them to make them actually do the changes and create the new pagefile.sys with the size I want:

```
RUN mkdir C:\SWAPS
RUN wmic pagefileset create name="C:\SWAPS\pagefile.sys"
RUN wmic pagefileset where name="C:\\SWAPS\\pagefile.sys" set InitialSize=128000,MaximumSize=256000
RUN wmic pagefileset where name="C:\\pagefile.sys" delete
```

**Comment by dcantah** [comment]
Hey! @chaotive Are you running your workloads on k8s by any chance? And to drill into the 

> because I can't do reboot after running the command line parameters required to make it work.

do you mean this is unacceptable for your workloads for the host to reboot (even once to set this up initially) or you mean you can't because you can't access the host to set this, and you're not able to reboot the host afterwards from within a container.

**Comment by chaotive** [comment]
> Hey! @chaotive Are you running your workloads on k8s by any chance? And to drill into the
> 
> > because I can't do reboot after running the command line parameters required to make it work.
> 
> do you mean this is unacceptable for your workloads for the host to reboot (even once to set this up initially) or you mean you can't because you can't access the host to set this, and you're not able to reboot the host afterwards from within a container.

Hi. Thanks for the reply. Everything is acceptable, but the problem is that:

1. Restarting the container does not work as a real Windows reboot, it simply loads it from the original state, not applying the pending changes I had. 
2. Performing shutdown -r makes the container to be killed, not rebooted from within. Next start is as if it was from original state.
3. Also, problem is the same if I apply these changes on the build script. Starting the container does not really "startup" it, it simply makes as if it was continuing after the initial installation, without rebooting. Not sure if this how Windows container behave or something to do with this image.

**Comment by dcantah** [comment]
Right, the reason I'm asking about k8s is because we support a container type named [hostprocess](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/) containers that is able to make host changes like privileged containers on linux. Reason being is I don't believe pagefile settings are per container, they piggy back off the host setting and location by default as far as I remember so if you were able to edit what you need on the host and reboot, your containers should pick up these changes

**Comment by chaotive** [comment]
> Right, the reason I'm asking about k8s is because we support a container type named [hostprocess](https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/) containers that is able to make host changes like privileged containers on linux. Reason being is I don't believe pagefile settings are per container, they piggy back off the host setting and location by default as far as I remember so if you were able to edit what you need on the host and reboot, your containers should pick up these changes

Well, did not considered using k8s at this time, I guess that is something I can explore if no more direct solution exists. So, you mean pagefile.sys can't be changed as part of the image/container configuration?

**Comment by dcantah** [comment]
I can verify, but as far as I know it's a host setting and as you've found (and should stay the case 😆) reboot in a container just effects the container itself
