### ISSUE TITLE
Powershell Constrained Language Mode is inconsistent between process and hyperv isolation. 

### ISSUE THREAD

**Issue by mbelt** [microsoft/Windows-Containers#283]
**Describe the bug**
When building a docker image with `--isolation hyperv` the [Powershell Constrained Language Mode](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/) is altered. 

**To Reproduce** 
```
PS > docker run --isolation hyperv --entrypoint powershell mcr.microsoft.com/windows/servercore:ltsc2022 echo $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage
``` 
Ok.
```
PS > docker run --isolation process --entrypoint powershell mcr.microsoft.com/windows/servercore:ltsc2022 echo $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage
``` 
Ok. 
``` Dockerfile
FROM mcr.microsoft.com/windows/servercore:ltsc2022
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN echo $ExecutionContext.SessionState.LanguageMode
```
```
PS > docker build --isolation process  --no-cache=$true .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM mcr.microsoft.com/windows/servercore:ltsc2022
 ---> 06bb218927a8
Step 2/3 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in f14e82e8b8b4
Removing intermediate container f14e82e8b8b4
 ---> d56812725126
Step 3/3 : RUN echo $ExecutionContext.SessionState.LanguageMode
 ---> Running in 8ad9e234c89f
ConstrainedLanguage
```
Ok.
```
PS > docker build --isolation hyperv  --no-cache=$true .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM mcr.microsoft.com/windows/servercore:ltsc2022
 ---> 06bb218927a8
Step 2/3 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in b5ae063e8187
Removing intermediate container b5ae063e8187
 ---> e1c015c0bc2e
Step 3/3 : RUN echo $ExecutionContext.SessionState.LanguageMode
 ---> Running in b46656491282
FullLanguage
```
What?

**Expected behavior**
Constrained Language Mode should be consistent between `docker build` and `docker run`.
 Constrained Language Mode should be consistent between `--isolation process` and `--isolation hyperv`

**Configuration:**
Windows Version	10.0.22621 Build 22621
Image mcr.microsoft.com/windows/servercore                     ltsc2022                         06bb218927a8
Container engine: docker
```
PS > docker version
Client:
 Cloud integration: v1.0.24
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.10.1 (82475)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:03:58 2022
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by fady-azmy-msft** [comment]
Hey @judyliu-ms, any thoughts on this?

**Comment by judyliu-ms** [comment]
Hi @mbelt thanks for capturing this, we will be investigating internally - for MS folks internal tracking #43089806

**Comment by iankingori** [comment]
Hey @mbelt

For the first issue - **Constrained Language Mode should be consistent between docker build and docker run:**

- PowerShell on Windows Containers defaults to FullLanguage and is consistent between docker run and docker build. This can be confirmed by running the same command on cmd instead of PowerShell :` docker run --isolation hyperv --entrypoint powershell mcr.microsoft.com/windows/servercore:ltsc2022 echo $ExecutionContext.SessionState.LanguageMode`
- In PowerShell, the above command is impacted by variable substitution so when Language Mode on the host is `ConstrainedLanguage`  we effectively run `echo ConstrainedLanguage`. You can avoid this by escaping the variable using `` `$ExecutionContext.SessionState.LanguageMode``
- This is not unique to the LanguageMode and can be reproduced using `$HOME` variable as well and you'll get the host home path instead of the container:  `docker run --isolation hyperv --entrypoint powershell mcr.microsoft.com/windows/servercore:ltsc2022 echo $home`
