### ISSUE TITLE
Windows Server Core images "40% smaller"?

### ISSUE THREAD

**Issue by ChaseB-CF3D** [microsoft/Windows-Containers#291]
Hello, 

In an effort to minimize our CI/CD runtimes, I am attempting to slim down our base OS image sizes. When doing research related to this, I encountered articles such as https://techcommunity.microsoft.com/t5/containers/making-windows-server-core-containers-40-smaller/ba-p/1058874 and https://devblogs.microsoft.com/dotnet/we-made-windows-server-core-container-images-40-smaller/ making claims of images which are "40% smaller". 

After digging into this, I see that the insider images presented in the articles are in fact ~40% smaller, but this does not seem to get carried into the stable repo images, as the articles indicate. On top of that, I am not able to find any further information as to why these smaller image sizes are not carried into the stable repo. Am I missing something here? Are these smaller images available elsewhere and available for use under the same license as the stable repo images?

Thanks.

**Comment by ohault** [comment]
According to the recent strategic commitment of Microsoft in [accelerating progress toward a more sustainable future](https://www.microsoft.com/en-us/sustainability/approach), this is going to be changed?

The current Windows Containers design and implementation are deeply impacted by that, as you underlined. And indeed, the current mandatory and obscure Windows Containers base images boatware is a huge problem.

There is here a real and serious [Sustainable Software Engineering (SSE)](https://devblogs.microsoft.com/sustainable-software/sustainable-software-engineering-sse-and-the-role-and-responsibilities-of-a-sustainable-software-engineer/) challenge and not limited to Windows Containers.  

In very short term, there is no other option than to have access to the image generation scripts/processes of those images (see https://github.com/microsoft/Windows-Containers/issues/222) because intriguingly only a next major version of Windows Containers would be able to fix this issue and for that Windows architecture still need some key investments into building a real namespaces support, a new network stack, ... that according to me will not be available before a few years.

**Comment by michbern-ms** [comment]
Good news -- please see our announcement this week about a new reduction in size on base images:
https://techcommunity.microsoft.com/t5/containers/reducing-the-size-of-windows-server-container-images-part-1/ba-p/3712738

Thanks,
Michael

**Comment by slonopotamus** [comment]
@michbern-ms As you say, it is a **new** reduction.

Quoting your url:

> **Over the past few months**, we've worked hard to decrease the size of the Windows container base images

But this doesn't answer anything about where **old** reduction from 2019 has disappeared.

**Comment by michbern-ms** [comment]
The best I can do here is to assure you that the latest Server 2019 and Server 2022 images have all of the optimizations that are available to us.  Both products are under continuous servicing for security fixes and critical customer needs.  Sometimes a fix for a security vulnerability might need to make a binary larger.   Which means that the base image might also grow larger.  As you noted in the article linked above, Server 2019 GA had a compressed image of 1.92 GB.  The first wave of reduction made it smaller, but servicing over time chipped away at the size reduction.  As of December 2022, the compressed image was at 1.74 GB.  With the new reduction, we are down to 1.54 GB.  

If the "old reduction" had truly been lost, the December 2022 image would have been 1.92 GB or larger.

Thanks,
Michael
