### ISSUE TITLE
Get-Credential hangs in mcr.microsoft.com/windows/servercore:2004-amd64

### ISSUE THREAD

**Issue by leitzler** [microsoft/Windows-Containers#300]
**Describe the bug**
I run a clean servercore container in Azure and executes `Get-Credential` and it hangs.

Let me know if this isn't the right place for this bug report and I'll be happy to move it to the right place (Azure somewhere?).

**To Reproduce**
Start a clean container: 
`az container create --resource-group <..> --name <..> --image mcr.microsoft.com/windows/servercore:2004-amd64 --os-type Windows`
Inside, run `Get-Credential`:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\> Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
```

**Expected behavior**
I expect a username & password prompt.

**Configuration:**
 - Edition: Azure container
 - Base Image being used: Windows Server Core
 - Container engine: Azure built in

**Additional context**
-

**Comment by fady-azmy-msft** [comment]
Hey @leitzler thank you for raising this bug issue. We're looking into this issue, and I created an internal issue (ID: 42619607) to track this.

**Comment by pbozzay** [comment]
Hi @leitzler ,

By default, Get-Credential displays a popup dialog to the user (where credentials can be gathered). In a container, there is no UI, so there is nowhere for this dialog to be responded to. As a result, powershell hangs waiting for a response from the user. 

Instead, try changing powershell's policy to accept credential input in the console session, like this:
```
PS C:\> $key = "HKLM:\SOFTWARE\Microsoft\PowerShell\1\ShellIds"
PS C:\> Set-ItemProperty -Path $key -Name ConsolePrompting -Value $true
PS C:\> $c = Get-Credential
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
User: test
Password for user test: ****
```

Internally, I'll start some discussion about whether we could simply make this the default setting for powershell in containers, since ultimately a popup will be useless in this context.
