### ISSUE TITLE
Windows and Linux at the same time

### ISSUE THREAD

**Issue by mhsimkin** [microsoft/Windows-Containers#318]
When using Windows 11 and Docker Desktop, there is a restrictions that you cannot run both Linux and Windows based containers at the same time.  Does this restriction also exist on Windows Server 20xx?

It would be helpful to have all this information in the documentation, including how containers on Windows 11 differ from containers on Windows Server.

Thanks.

**Comment by hach-que** [comment]
As an FYI, [RKM](https://src.redpoint.games/redpointgames/rkm) will run Linux and Windows containers on the same Windows 11 machine when Windows is the Kubernetes master, by leveraging WSL for the Linux kubelet. So it's definitely possible to do what you want, it's likely that it's just a configuration that Docker Desktop doesn't support.

**Comment by lippertmarkus** [comment]
You can manually install docker on both WSL and Windows and use them simultaneously: https://lippertmarkus.com/2021/09/04/containers-without-docker-desktop/

**Comment by hach-que** [comment]
I should note that since writing my original comment about RKM, there are a few issues outstanding that prevent it from truly working across Windows+WSL:

- https://github.com/microsoft/WSL/issues/9732
- https://src.redpoint.games/redpointgames/rkm/-/issues/9
- https://src.redpoint.games/redpointgames/rkm/-/issues/3
- https://src.redpoint.games/redpointgames/rkm/-/merge_requests/3

Plus you can hit a blue screen if you unblock WSL from the VXLAN-configured Hyper-V switch and a Windows container then terminates. I can usually hit that about 50% of the time, but I haven't spent further time investigating it since the other WSL issues get in the way at the moment.

**Comment by mhsimkin** [comment]
My original ask has not been answered.  I want to understand if containers on Windows Server 2019/2022 have the same restriction as stated in the documentation.  

Can I run windows based and linux based containers on Windows Server?

**Comment by lippertmarkus** [comment]
WSL is also available on Windows Server so everything described above works there as well.

**Comment by vrapolinario** [comment]
@mhsimkin You can, in theory, run Windows containers and Linux container side by side on Windows Server. A few things to note:
- Windows containers would be installed normally, while Linux containers would have to run on WSL 2.
- WSL 2 runs on a utility VM, so technically, they are not really side by side.
- WSL 2 is supported for development and testing purposes, not production.

I have blogged about this here: https://techcommunity.microsoft.com/t5/itops-talk-blog/using-wsl-2-on-windows-server-2022-to-run-linux-containers/ba-p/3624745

**Comment by mhsimkin** [comment]
@vrapolinario Thank you. I will have to read your blog and try it.
