### ISSUE TITLE
git error "fetch-pack: unexpected disconnect while reading sideband packet" on ws2022 inside ltsc2022 container

### ISSUE THREAD

**Issue by mawl** [microsoft/Windows-Containers#320]
Hi there,

**Describe the bug**
When cloning a medium to large size git repo over https inside a running docker container ltsc2022, the following error occurs and the repo doesn't get cloned.
```
...
09:06:42.609694 run-command.c:655       trace: run_command: git index-pack --stdin --fix-thin '--keep=fetch-pack 7536 on runner-swdsajak-project-7441-concurrent-1' --pack_header=2,243425
09:06:42.619642 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/git/mingw64/bin
09:06:42.621201 git.c:460               trace: built-in: git index-pack --stdin --fix-thin '--keep=fetch-pack 7536 on runner-swdsajak-project-7441-concurrent-1' --pack_header=2,243425
09:14:22.632711 http.c:703              == Info: HTTP/2 stream 7 was not closed cleanly before end of the underlying stream
09:14:22.637595 http.c:703              == Info: Connection #0 to host git.d-velop.de left intact
error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly before end of the underlying stream
error: 45760 bytes of body are still expected
09:14:22.637595 pkt-line.c:80           packet:          git> 0002
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```
This error does not occur on:
* windows server 2019 inside a docker container
* windows server 2022, when using git clone on the host system and not inside a container

**To Reproduce** 
```
>docker run -it --rm --entrypoint="" gitlab/gitlab-runner-helper:x86_64-bleeding-servercore21H1 powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
> git clone https://git.ourcompany.com/some-group/some-repo.git (repo size > 100MB)
Cloning into 'some-repo'...
Enter basic credentials for 'https://git.ourcompany.com/':
Username: ...
Password:
remote: Enumerating objects: 348997, done.
remote: Counting objects: 100% (8310/8310), done.
remote: Compressing objects: 100% (2608/2608), done.
fatal: fetch-pack: invalid index-pack output.69 MiB | 1.66 MiB/s
fetch-pack: unexpected disconnect while reading sideband packet
> ^C
```

For more output use:
```
> $env:GIT_TRACE_PACKET=1
> $env:GIT_TRACE=1
> $env:GIT_CURL_VERBOSE=1
```

**Expected behavior**
The repo gets cloned and everything works fine :)

**Configuration:**
 - Edition: windows server 2022
- Base Image being used: Windows Server Core
 - Container engine: docker
 - Container Engine version 20.10.22 - 23.0.1
 - git version (inside docker image) 2.38.1 - 2.39.1

**Additional context**
This describes workarounds which aren't functional for our case:
- https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet/67390274

Any ideas?

**Comment by Duks31** [comment]
Same problem i have. Please did you find an answer?.

**Comment by mawl** [comment]
Any news/hints for us? This is a showstopper and forces us to revert to ltsc2019 images on windows server 2019 for our CI Builds.

**Comment by fady-azmy-msft** [comment]
Looking into this. I made an internal ticket (#44339443) for tracking.

**Comment by speedym** [comment]
I'm also seeing a similar issue, 100% reproducible for a certain job, when actions/checkout@v3 is checking out submodules from a private repo:
```
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  Error: fatal: clone of 'git@github.com:xxx' into submodule path 'D:/a/yyy' failed
  Failed to clone 'zzz'. Retry scheduled
  Cloning into 'D:/a/yyy'...
  fetch-pack: unexpected disconnect while reading sideband packet
  Error: fatal: early EOF
  Error: fatal: fetch-pack: invalid index-pack output
  Error: fatal: clone of 'git@github.com:xxx' into submodule path 'D:/a/yyy' failed
  Failed to clone 'zzz' a second time, aborting
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 1
```

**Comment by sbangari** [comment]
@mawl What is the network mode you are using? Is it the NAT network mode?

**Comment by ghost** [comment]
@mawl, Unfortunately, I have not been able to reproduce this issue on my end. Things I've tried on my end:

1. Ran docker run -it --rm --entrypoint="" gitlab/gitlab-runner-helper:x86_64-bleeding-servercore21H1 powershell on a Windows Server 2022 machine.
2. Tried "git clone ". The public repo I used was "https://github.com/microsoft/MixedRealityToolkit-Unity" which has a pretty big size. This worked without issues.
3. Forked the repo: "https://github.com/microsoft/MixedRealityToolkit-Unity" and added a few large files (greater than 10 MB in size). Tried to clone the updated repo and this too worked without issues.

Additionally, I also tried with different versions of Docker, Git, container images, and VMs based on the information provided under "Configuration." I also attempted to clone private repos. None of these things helped me to reproduce the issue.

Since at this point, I'm not able to make any progress, I have the following requests for you:

1. Can you try to clone the public repo mentioned above to see if the issue reproduces on your end? Also, is it possible to share a public repo for which this is reproducible?
2. Could you highlight any noticeable difference between your repo and the public one?

**Comment by mawl** [comment]
@vagokuln-msft, error during git clone happened on my side with https://github.com/microsoft/MixedRealityToolkit-Unity, too.

I have tested it on windows server 2022 VMs hosted on vmware vsphere and vcloud.

Maybe that's the clue? Is it possible for you to test it on the vmware stack?

P.S. Docker is installed by:
* vcloud: https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1
* vsphere ESXi: https://community.chocolatey.org/packages/docker-engine

**Comment by mawl** [comment]
> @mawl What is the network mode you are using? Is it the NAT network mode?

@sbangari, sounds like NAT is the default network under windows: https://learn.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture

I have made no changes there.

**Comment by nagaye-wisdom** [comment]
this usually happens when the internet reception is not strong. try with high speed internet

**Comment by jinshang-msft** [comment]
Hi @mawl, I am taking over the remaining work for @vagokuln-msft. I cannot repro the issue on my WS2022 VM either. I will try it on vSphere and will keep you posted.

**Comment by jinshang-msft** [comment]
Hi @mawl, I have installed a WS2022 VM instance on vSphere and ran the said failing commands in the container. However, I still haven't been able to repro the issue.

One thing I want to confirm with you. What compatibility option did you choose when creating the VM instance on your side? I was using **ESXi 7.0 U2 and later**.

Also, since I cannot get a repro for now, can you also try this on your side?

1. Download [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) to your host VM
2. Open it with the filter below.
    Column            Relation            Value            Action
    Process Name  is                      svchost.exe   Include
3. Run the git clone command inside the container
4. Check if there is any warning or error shown in the Process Monitor window

While I will keep trying the repro, please also let me know if you could find anything interesting on your side.

**Comment by mawl** [comment]
Hi @jinshang-msft,

Thank you for your help.

We are using the same compatibility option ESXi 7.0 U2 and later for our VMs.

So, here are some results shown during the svchost capture:

INVALID PARAMETER, BUFFER TOO SMALL, FILE LOCKED WITH ONLY READERS, NAME COLLISION, STORAGE RESERVE DOES NOT EXIST, SHARING VIOLATION...

And an UNSUCCESSFUL in detail:
```
svchost.exe	C:\Windows\System32\svchost.exe -k utcsvc -p	DeviceIoControl	\Device\VhdHardDisk{dd7c5346-065c-495f-a2cd-cf6b7753b8d5}	INVALID DEVICE REQUEST	Control: IOCTL_DISK_GET_DRIVE_GEOMETRY_EX	File System	
svchost.exe	C:\Windows\System32\svchost.exe -k utcsvc -p	DeviceIoControl	\Device\VhdHardDisk{dd7c5346-065c-495f-a2cd-cf6b7753b8d5}	UNSUCCESSFUL	Control: IOCTL_STORAGE_QUERY_PROPERTY	File System	
```

Do you have a hint for me, which events can be relevant, to give you more details on that? The whole list is too long for posting it here.

For completeness, we have tested the said failing commands on Windows Server 2022 OS without using virtualization. There, we have no issues, so it sounds to me, that it only occurs on VMs.

**Comment by jinshang-msft** [comment]
The error code 'BUFFER TOO SMALL' looked suspicious. Can you run this command and check what the size of post buffer is for GIT in the affected image?

git config --get http.postBuffer

**Comment by mawl** [comment]
> The error code 'BUFFER TOO SMALL' looked suspicious. Can you run this command and check what the size of post buffer is for GIT in the affected image?
> 
> git config --get http.postBuffer

The error in detail:
`12:38:00,0088855	svchost.exe	1468	RegQueryKeySecurity	HKLM\SOFTWARE\Microsoft\Windows	BUFFER TOO SMALL`

`git config --get http.postBuffer` is empty, default is 1MiB. But I don't think that's the case here as the error doesn't occur on the same default setup with ltsc2019 - and we already have tried various git option: https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet/67390274

**Comment by jinshang-msft** [comment]
Hi @mawl,

I would like to bring the discussion back to reproducing the issue. Since this image is a custom one on top of relatively old base image layers. I want to make sure the base OS itself is good.

Can you pull these 2 container images, one is the old one and the other is the latest? Then install GIT and try 'git clone' operation again in those containers?

docker pull mcr.microsoft.com/windows/servercore:10.0.20348.1607
docker pull mcr.microsoft.com/windows/servercore:ltsc2022

You can install GIT by downloading the [portable GIT version](https://git-scm.com/download/win), unzip it and add the file fold to your PATH.

Please let me know if this issue can still be reproed inside these 2 containers. 

Thanks,
Jinchuan

**Comment by mawl** [comment]
Hi @jinshang-msft,

I have used chocolatey for installing git:
```
# escape=`

#ARG VERSION=10.0.20348.1607
ARG VERSION=ltsc2022
FROM mcr.microsoft.com/windows/servercore:${VERSION}

# https://docs.chocolatey.org/en-us/choco/release-notes
ENV chocolateyVersion 1.4.0
ENV ChocolateyUseWindowsCompression true

RUN `
    # install chocolatey
    @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && `
    SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" && `
    refreshenv

# with and without --params "/SChannel"	
RUN choco install -y git --version 2.41.0
```

But unfortunately same issue with both image versions:
```
Microsoft Windows [Version 10.0.20348.1850]
(c) Microsoft Corporation. All rights reserved.

C:\>git clone https://github.com/microsoft/MixedRealityToolkit-Unity
Cloning into 'MixedRealityToolkit-Unity'...
remote: Enumerating objects: 327195, done.
remote: Counting objects: 100% (3279/3279), done.
remote: Compressing objects: 100% (1780/1780), done.
fatal: fetch-pack: invalid index-pack output7 MiB | 135.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
```

**Comment by jinshang-msft** [comment]
That's unfortunate. I will try again with reproing it on vSphere. Will get back to you.

In the meantime, is it possible for you to test it on another hypervisor stack, like Hyper-V? Or you can create a Win Server VM resource on Azure for testing.

**Comment by jinshang-msft** [comment]
Hi,

We are unable to reproduce the issue you described on our side with the VM environments as below.

Host: Windows Server 2022 on Hyper-V
Container Image: gitlab/gitlab-runner-helper:x86_64-bleeding-servercore21H1 based on Server Core
Container Engine: Docker 24.0.2
Git repo to pull: https://github.com/microsoft/MixedRealityToolkit-Unity

Host: Windows Server 2022 on vSphere (compatibility option ESXi 7.0 U2 and later)
Container Image: gitlab/gitlab-runner-helper:x86_64-bleeding-servercore21H1 based on Server Core
Container Engine: Docker 24.0.2
Git repo to pull:https://github.com/microsoft/MixedRealityToolkit-Unity

We would recommend you review the setup in your environment and let us know if there is anything missing in our previous discussion.

**Comment by fady-azmy-msft** [comment]
Closing this because issue is going stale.

**Comment by mawl** [comment]
Finally, after some VMWare Updates and new generations of VMs the issue is solved for us now. 🎉

**Comment by DJStompZone** [comment]
Yes but HOW
