### ISSUE TITLE
windows/server:ltsc2022 is 2.2 GB larger than 6 weeks ago

### ISSUE THREAD

**Issue by mloskot** [microsoft/Windows-Containers#321]
## Why sizes of the images have increased so much?

I'm `docker pull`-ing updates of the three Microsoft images, all for `ltsc2022` tag, and I noticed sizes of these two have increased significantly:

1. mcr.microsoft.com/windows/server:ltsc2022 from 7.46 GB to **9.7** GB
2. mcr.microsoft.com/windows/servercore:ltsc2022  from 3.08 GB to **3.85** GB

Here is the detailed list where the `<none>` is the `ltsc2022` from 6 weeks ago:

```console
docker image ls | findstr "windows/" | sort
mcr.microsoft.com/windows/nanoserver   <none>                           ab6b2955d60a   6 weeks ago   297MB
mcr.microsoft.com/windows/nanoserver   ltsc2022                         32002da5756a   2 weeks ago   297MB
mcr.microsoft.com/windows/server       <none>                           3bd08594965c   6 weeks ago   7.46GB
mcr.microsoft.com/windows/server       ltsc2022                         668a3f272e96   2 weeks ago   9.7GB
mcr.microsoft.com/windows/servercore   <none>                           1fb25eb608ab   6 weeks ago   3.08GB
mcr.microsoft.com/windows/servercore   ltsc2022                         903e6f2eff2a   2 weeks ago   3.85GB
```

**Comment by akarshm** [comment]
Hey Mateusz, this is an expected size increase since the Jan 2023 image did not have the delta layer, but the Feb 2023 images have. You can read more [here](https://techcommunity.microsoft.com/t5/containers/reducing-the-size-of-windows-server-container-images-part-1/ba-p/3712738) and [here](https://techcommunity.microsoft.com/t5/containers/reducing-the-size-of-windows-server-container-images-part-2/ba-p/3741795), but we expect the base layer to remain cached while the smaller delta layer will significantly reduce the image pull time.

**Comment by mloskot** [comment]
@akarshm Thank you for the explanation and the links. It's very informative indeed. I'm happy to close this issue as addressed.
