### ISSUE TITLE
Security patches not applied to the latest Windows server core 2022 container image

### ISSUE THREAD

**Issue by tarekmulla** [microsoft/Windows-Containers#372]
**What is your question?**
I am using the latest windows server core 2022 image from here: https://hub.docker.com/_/microsoft-windows-servercore (tag ltsc2022)

After checking the available updates on this image tag (ltsc2022), it shows that the KB5012170 (Security update) and KB5026370 (Cumulative update) are not applied. 
**1.Why are there missing updates when I use the latest image?**

ltsc2022 image - showing missing security and cumulative patches:
![Screenshot 1](https://github.com/microsoft/Windows-Containers/assets/8681571/fa35324b-8645-4298-a568-d1f45af05202)

 

I then went ahead and deployed another image with tag (ltsc2022-KB5026370). Using this image, it no longer shows the outstanding KB5012170 (security update), however, it shows the KB5026370 (Cumulative update) is still missing.
**2.When using this specific Image, why is there still missing patches? and the missing one (KB5026370) has same name of the image tag (ltsc2022-KB5026370)**

ltsc2022-KB5026370 image, showing missing cumulative patches:
![Screenshot 2](https://github.com/microsoft/Windows-Containers/assets/8681571/8e43d54c-d22e-482f-a9b0-bc8be573182b)

However, if you go to this page https://hub.docker.com/_/microsoft-windows-servercore, under the Full Tag Listing, it shows that the ltsc2022-KB5026370 and ltsc2022 images are both updated on the same day (05/09/2023).

**3.How can two separate images that are updated on the same day, be released with different patches missing (as per the above two questions)?**

**Comment by akarshm** [comment]
Hi Tarek, the featured tag for Windows Server 2022 Server Core container image (_docker pull mcr.microsoft.com/windows/servercore:ltsc2022_) should always pull the latest image. I see that these images have the latest security fixes. The release notes for Windows Server Containers are available [here](https://prod.support.services.microsoft.com/en-us/topic/kb5026703-windows-server-containers-for-may-2023-93bbde6f-6d3c-45b3-a6b1-391e9ca8af30).

![image](https://github.com/microsoft/Windows-Containers/assets/7432288/0ad128da-8aeb-415c-a6e1-3e074ec74e2c)

**Comment by tarekmulla** [comment]
Hey @akarshm , 
Thank you for your help in this question. I really appreciate your quick response.

I did a test, and you are right, it is showing as part of the hotfixes. However, it is still showing KB5026370 is missing in both tags ltsc2022 and ltsc2022-KB5026370, and with size 24GB! is there an explanation for that? 

ltsc2022:
![image](https://github.com/microsoft/Windows-Containers/assets/8681571/364ab9e6-a7fe-446b-aa4b-e452660f0b84)


ltsc2022-KB5026370:
![image](https://github.com/microsoft/Windows-Containers/assets/8681571/24b12654-5b98-46d9-84a4-10769e4a2224)

Also, you can see that there is an outstanding security update (KB5012170) in the ltsc2022 tag, is this expected in ltsc2022 tag? 


Thank you so much, 
Tarek

**Comment by akarshm** [comment]
Hi Tarek, there are a number of questions nested here, so let me attempt to answer each one of them separately:

1. The image you downloaded with the LTSC2022 tag must have been downloaded before May 9, 2023. At that time, the latest image was from April 2023, and that was served to you. Since containers cannot update themselves 'in place' (like a laptop or mobile phone), it couldn't fetch May 2023 (KB5026370) update when it was available. We expect customers to pull new container images each month from Microsoft Artifact Registry (mcr.microsoft.com/windows/servercore:ltsc2022). The installed-on date, therefore, points to Apr 5, 2023.

2. The image you downloaded with the LTSC2022-KB5026370 has the KB number mentioned explicitly and correctly pulled the May 2023 image. Get-HotFix clearly shows that security update KB5026370 was installed. This matches the screenshot I shared in my previous response.

    To be clear, LTSC2022 and LTSC2022-KB5026370 pull the exact same image (SH256-wise) today, but the former is a featured (floating) tag (so it will point to a different image as updates are released), while the latter is an explicit tag (so it will always pull the May 2023 image).

4. [KB5012170](https://support.microsoft.com/en-us/topic/kb5012170-security-update-for-secure-boot-dbx-72ff5eed-25b4-47c7-be28-c42bd211bb15) refers to an out-of-band update that Microsoft released in 2022 to address a vulnerability in Secure Boot Forbidden Signature Database (DBX). Since Windows updates are cumulative in nature, the update from last month automatically rolls up to the next month. Since the latest (May 2023) security update (KB5026370) is already installed, the container image already has the fix. 😃 

    Also, note that Windows container images don't have secure boot enabled.
    ![image](https://github.com/microsoft/Windows-Containers/assets/7432288/0efd0073-7b6c-4f61-b104-65dd50ebdda6)

**Comment by ntrappe-msft** [comment]
@tarekmulla Just checking in, did Akarsh's comment help clarify how security patches work and what your next steps should be? If not, please let us know.

**Comment by tarekmulla** [comment]
Hey @ntrappe-msft and @akarshm 
Thank you so much for the help with this question, and with the follow up. 

Yup, all good, @akarshm 's answer addressed my question, I am going to close the issue.

Cheers,
Tarek
