### ISSUE TITLE
-NoRestart does not complete the installation / script is difficult to call from higher level orchestrating automation

### ISSUE THREAD

**Issue by DarwinJS** [microsoft/Windows-Containers#396]
Please fill out _all the sections_ below for bug issues, otherwise it'll be closed as it won't be actionable for us to address.

**Describe the bug**
Generally when using a parameter like -NoRestart - one does not expect the installation to be incomplete. However, this script does not schedule the post-reboot task.

I think this will lead to many bug reports here as it will be commonplace to assume a -NoRestart parameter does not materially affect the installation activities that are supposed to be done for a fully functional install.

On a very related note, it is difficult to automate these scripts and give a success error code to the parent process. Since a mid-install reboot is required, the original caller will receive an error when it is terminated by a reboot and it will not restart the original caller. => Which leads to looking for and using the -NoRestart switch.

**To Reproduce** 
Attempt to have a complete and proper install of any of these options and a non-error return code from an orchestration script.

**Expected behavior**
It should be possible to orchestrate this AND not always have to make it the last step.
Suppressing reboots should not result in a known-broken install - especially since when using remote execution, the warning message won't be seen until after a lot of root cause analysis.

The official docs talk about the Azure Custom Script Extension as though it is supported: https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=containerd#custom-script-extensions - but I'm wondering if it has been tested with this code because I'm not having success.

**Configuration:**
 - Edition: Windows Server 2022
- Base Image being used: Windows Server Code
 - Container engine: docker (but all 3 installers seem to have this behavior)
 - Container Engine version 24.1

**Additional context**

**Comment by iancward** [comment]
Seems like you're using Azure, but AWS EC2 Image builder has support to perform a managed restart with Exit Code 3010.

- https://docs.aws.amazon.com/imagebuilder/latest/userguide/toe-action-modules.html#action-modules-executepowershell
- https://docs.aws.amazon.com/systems-manager/latest/userguide/send-commands-reboot.html

We followed the example (write a reboot indicator file, run the docker install script with `-NoReboot`, exit 3010, then start back and re-run the script and finish the setup) and things are working pretty well.

We actually had this logic in place with the old MicrosoftDockerProvider OneGet provider (since both installation methods depend on the Containers feature) and we just swapped the commands out to download and run the helper script instead.

**Comment by jupan-msft** [comment]
I'm not sure if Custom Script Extension support orchestrating steps after reboot, but you should be able to do that with [DSC](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-windows). And I found a sample in Stackoverflow [here](https://stackoverflow.com/a/37016959).
