### ISSUE TITLE
Windows images are restarting

### ISSUE THREAD

**Issue by saiben10** [microsoft/Windows-Containers#403]
Windows images are restarting when i am trying to deploy in the cluster the pod is going up and again going down like wise it was happening

**Comment by fady-azmy-msft** [comment]
Can you share repro instructions that triggered the images to restart?

**Comment by saiben10** [comment]
Hi @fady-azmy-msft , this is the image i am trying to pull.
 docker pull mcr.microsoft.com/windows/servercore:ltsc2022

**Comment by fady-azmy-msft** [comment]
Can you also share the steps you took that triggered this bug?

**Comment by saiben10** [comment]
Basically when I am trying this image as a Jenkins pod it is not running
Linux images are running fine
Only windows images are getting issue

**Comment by fady-azmy-msft** [comment]
I'm afraid I'll need a bit more details on your repro steps just to make sure we repro the same setup. See this issue as an example [of repro steps](https://github.com/microsoft/Windows-Containers/issues/360).

**Comment by saiben10** [comment]
Hello, @fady-azmy-msft  i have been using the different windows images mcr.microsoft.com/windows/servercore:ltsc2022 this is one of the image of them . But when i used this image in the kubernetes pod the pod is restarting multiple times. same with all windows images what might be the issue.
can you please clarify.

**Comment by ntrappe-msft** [comment]
Hi, I'm trying to understand your situation a bit more. Correct me if I'm wrong but I'm assuming that you're:
- using a Jenkins server to build, test, and deploy Windows Containers (specifically Windows Server Core 2022)
- connecting that Jenkins server AKS
- AKS is managing your pod of Windows Containers

If you're **not** using AKS to manage your pod and connect Jenkins as a CI/CD server, we may ask you to first trying deploying the pod with AKS then connecting Jenkins. If you are using AKS, did you first check to see that normally deploying a pod worked before connecting the CI/CD component?

**Comment by saiben10** [comment]
Hello @ntrappe-msft for me the pod is creating with linux images. But only the issue is i am unable to run windows images it is saying unable to pull the  image.
can you please clarify that can we run more than two windows images in a single pod

**Comment by ntrappe-msft** [comment]
Thanks for explaining your problem a bit further. What I'm hearing is that you:
- Have a Kubernetes cluster with a Linux node as the host
- Will be running both Linux and Windows Containers in this cluster
- When you try to pull a Windows container image, you're getting an error message

If all the above is true, then there is a problem. **All containers in a pod or cluster must share the same host operating system.** However, Windows containers require a Windows host and Linux containers require a Linux host to run. **It's not possible to run Windows container images directly on a Linux node.**

When we see errors with failing to pull an image like `docker pull mcr.microsoft.com/windows/servercore:ltsc2022`, it's often because Docker Desktop is switched to "Linux containers" or another platform mismatch. In this case, it's stemming from an incompatible node type.

### Next Steps
You can create a Kubernetes cluster with both Windows and Linux nodes but you'll have to schedule your Windows containers to run on Windows nodes. Here are 2 resources to help you with this:

- [Windows & Linux Living Together in Kubernetes Cluster](https://stackoverflow.com/questions/52198722/windows-linux-living-together-in-kubernetes-cluster): Stack Overflow post on how to set up a cluster with both nodes using Docker, `kubeadm`, and `nodeSelector`.
- [Windows Containers in Kubernetes](https://kubernetes.io/docs/concepts/windows/intro/): Official documentation on how to include Windows nodes in a Linux cluster and how to schedule

**Comment by fady-azmy-msft** [comment]
Closing issue because it's going stale
