### ISSUE TITLE
Process isolation mode for Windows 10 21H2

### ISSUE THREAD

**Issue by js250841** [microsoft/Windows-Containers#406]
I would like to run containers in process isolation mode on my system, Windows 10 21H2 (10.0.19044.3086). I found this one to run in process isolation mode: mcr.microsoft.com/windows/nanoserver:2004.

Is this image the only option for process isolation mode? The documentation seems to suggest there are no options, so the fact that this image works may be a fluke. Actually, process isolation mode would be ideal for development for me. Hopefully there is an image specifically for my system.

**Comment by ntrappe-msft** [comment]
Hi, thanks for bring this to our attention! I can't answer your specific question about whether `nanoserver:2004` is the _only_ image that can be run in process isolation mode on Windows 10. @fady-azmy-msft would know more than I. However, I _can_ confirm that none of our Windows Server images support process isolation on Windows 10.

### Windows 10 Image Support
| Image                            | Hyper-V Isolation      | Process Isolation     |
| ---------------------- | -------------------- | ------------------- |
| Windows Server 2022 |  ❌ Not Supported   | ❌ Not Supported |
| Windows Server 2019 | ✅ Supported            | ❌ Not Supported |                              
| Windows Server 2016 | ✅ Supported            | ❌ Not Supported |

_Resource_: [_Windows Container Version Compatibility_](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2016%2Cwindows-10)

**Comment by fady-azmy-msft** [comment]
![image](https://github.com/microsoft/Windows-Containers/assets/105251651/2e132390-bce5-430f-a299-a89e79fe5ef4)

For Windows 10 version 2004, you can see the [different Nano Server base images](https://mcr.microsoft.com/en-us/product/windows/nanoserver/tags) that which matches the container host version (2004) with container image versions (2004). 

You can see there's a tag `2004-KB5008212`, and the [associated KB](https://support.microsoft.com/en-gb/topic/december-14-2021-kb5008212-os-builds-19041-1415-19042-1415-19043-1415-and-19044-1415-b46200db-74c3-450e-b200-51013957312a) (you can search the whole tag). We don't however recommend using a Nano Server 2004 version because Win 10 2004 is [out of support](https://support.microsoft.com/en-us/topic/end-of-service-statement-e440a698-de79-4ace-b53b-5a6a3e36685e), so we won't be able to help with bugs you face.

Instead if you can, we recommend upgrading to Win11 and Hyper-V isolation (as @ntrappe-msft recommended).

**Comment by js250841** [comment]
Thank you for your feedback. I was very hopeful to make my project work in Windows 10, but in the end, it requires Windows 11 no matter what I try.
