### ISSUE TITLE
Support Window 10 base image for Windows Service 2022

### ISSUE THREAD

**Issue by miaooss** [microsoft/Windows-Containers#440]
**Is your feature request related to a problem? Please describe.**

Based on a company policy we are still using Windows 10 and we need to update from Windows Server 2019 container to Windows Server 2022 container.

but the process of building locally is becoming a big issue since we cannot use Windows 10 to pull/run the Windows Server 2022 container

**Describe the solution you'd like**
Support for Windows 10 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fady-azmy-msft** [comment]
Hey @miaooss, thank you for sharing this feedback. Currently we all of our investments are focused on Win11, WS2022 and beyond. 

I've shared this request with the team, so we are aware of it. 

I'll close this issue for now since this isn't a priority at the moment, but we'll track this thread for any new comments.
