### ISSUE TITLE
docs for Host Compute Service (HCS) API + bindings ?

### ISSUE THREAD

**Issue by christian-korneck** [microsoft/Windows-Containers#46]
I wonder if there's a reference documentation for the Host Compute Service (HCS) C API and/or the Golang/.NET bindings for it? Both are mentioned here, but I lack to find any docs about it?

https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20170127-introducing-the-host-compute-service-hcs#feedback

(Just to say, I'm not looking to replicate Docker/Moby functionality but am - as a Docker on Windows user - interested in debugging/troubleshooting beyond what's currently possible with `hcsdiag.exe`).

**Comment by conioh** [comment]
This is super-critical.

[hcsshim](https://github.com/microsoft/hcsshim) is terrible, [dotnet-computevirtualization](https://github.com/microsoft/dotnet-computevirtualization) hasn't beenupdated for two years, and the header files in the Windows SDK are incomplete.

For example, [dotnet-computevirtualization](https://github.com/microsoft/dotnet-computevirtualization) uses `vmcompute!CreateSandboxLayer` but there's no prototype for it in `computestorage.h` (or any of the other `computeXxx.h` files).

Please provide a reasonable documentation and complete header files.

**Comment by conioh** [comment]
Another issue that's missing documentation is everything related to the foreign layers being used by Docker on Windows and HCS.

Lets say I downloaded a tar/gzip/whatever from mcr.microsoft.com. How do I extract it into a working layer that HCS will accept? How do I handle the data in `PaxHeaders.0`? I can guess, but I'd like to see it documented. Is there anything else that needs to be done?

**Comment by christian-korneck** [comment]
> hcsshim is terrible

I think the `hcsshim` README could get some improvement. I think a quickstart example for how to create and run a container with the example cmdline tools would be a great entry point.

After playing a bit with hcsshim, here's what helped me:

- the code is well commented, looking at it with godoc provides at least some reference: https://godoc.org/github.com/microsoft/hcsshim
or https://pkg.go.dev/github.com/microsoft/hcsshim

- what's still missing are examples or a quickstart guide. Fortunately there are some example cmdline tools in `/cmd` that show how to use the api. You can create and run a container by combining `docker pull` (to get nanoserver layers), `wclayer` (create container scratch volume out of nanoserver layers + writeable scratch layer) and `runhcs` (create, start/stop the container). To figure out the syntax for these tools you can look at the [tests](https://github.com/microsoft/hcsshim/blob/1869133ca498cb7f27813514c3e6642cb1d8e5fe/test/runhcs/e2e_matrix_test.go#L165). I also found the comments in [this issue](https://github.com/microsoft/hcsshim/issues/435) to be super helful.

**Comment by christian-korneck** [comment]
> Another issue that's missing documentation is everything related to the foreign layers being used by Docker on Windows and HCS.
> 
> Lets say I downloaded a tar/gzip/whatever from mcr.microsoft.com. How do I extract it into a working layer that HCS will accept? How do I handle the data in `PaxHeaders.0`? I can guess, but I'd like to see it documented. Is there anything else that needs to be done?

You can run `docker pull <image>` to get the layers (they're stored in `%programdata%`) and use them with `wclayer.exe` (from the `hcsshim` example tools). I think this should fully answer your question: 
https://github.com/microsoft/hcsshim/issues/435#issuecomment-455774190

**Comment by christian-korneck** [comment]
But - just to audit this issue a bit - what's entirely missing are docs for the "public" HCS C API (at least I couldn't find them yet).  I would have expected to find them next to the docs for all the other Win32 APIs.

**Comment by conioh** [comment]
I don't want to use `docker pull` nor any other docker command. Had I wanted to do this... I would have done it.

I want _developer_ documentation so that I could write _code_ that interacts with and uses the HCS.

I repeat again that hcsshim is terrible and the fake docs you linked to are useless. It's really hard to believe you looked at them before writing this.

![image](https://user-images.githubusercontent.com/10606081/90247092-89d50880-de3e-11ea-8482-790a393c7999.png)

Wow, that's useful.

![image](https://user-images.githubusercontent.com/10606081/90249826-d53de580-de43-11ea-98bf-41055926ef5c.png)

Great job documenting the function.

![image](https://user-images.githubusercontent.com/10606081/90249872-e686f200-de43-11ea-9d0d-7ee08304e658.png)

Oh, flavor. That's nice.

Once more the question is: Given the URL `https://mcr.microsoft.com/v2/windows/nanoserver/blobs/sha256:917fbf2da20dfdefe470dc5dfdda45b99a2ef3ded6f4986ed770cd3e9244d1cb`, how do I correctly get the file layout **OF THE BASE LAYER**. I'm not asking on how to create another layer based on top of it.

Also, the comments in the ticket you linked to seem to be pretty wrong. Just pull `mcr.microsoft.com/windows/nanoserver:2004-amd64` (for example) and look at all them pretty VHDXs:

![image](https://user-images.githubusercontent.com/10606081/90247979-60b57780-de40-11ea-95fa-cf8ba7de5544.png)

Remember the URL from a couple lines above? Do you see the VHDXs and the hives there? Because I don't. So where did they come from? Without them I'm getting from`ERROR_PATH_NOT_FOUND` from `CreateSandboxLayer`.

That's why I'm asking Microsoft for official documentation, rather than relying unclear, doubtfully correct comments by clueless commenters from god-know-who on the Internet (or trying to go through thousands of `if err == nil`s in the Docker source code which might actually be worse).

**Comment by christian-korneck** [comment]
> I don't want to use docker pull

as far as I can tell `pull` isn't provided by `hcs`, it's a higher level feature of Docker/Moby.

> how do I correctly get the file layout OF THE BASE LAYER

I don't think it's intended that users create their own Windows container base image from scratch. You have to use one of the Microsoft provided ones, like `windows/nanoserver`, `windows/servercore`, `windows`. It also wouldn't make much sense to create your own one from scratch. Unlike with Linux containers, there are no `FROM scratch` container images for Windows containers because you always need certain Win32 DLLs, registry hive files, etc to be able to even run the most minimal static linked Windows executable. The image that comes closest to a scratch image is the `nanoserver` one.

Pulling these base images from the `mcr.microsoft.com` registry is the only way to obtain them (afaik).

**Comment by christian-korneck** [comment]
@conioh I just wrote a quick blogpost [link](https://poweruser.blog/hands-on-windows-container-internals-c9782d0115ff) with an example for running a simple container. Maybe it helps with your problem (maybe not).

**Comment by weijuans-msft** [comment]
Just a quick update: our engineering team is in the process of documenting the HCS C APIs; however there is no plan to further maintain or document the .NET wrapper.  In fact, there will be limited documentation on Docker/Moby related APIs going forward. We are transitioning from Docker/Moby to containerD, hence I'd suggest the community to transition with us and leverage those higher level abstraction layers.

**Comment by cby-in-ict** [comment]
> > Another issue that's missing documentation is everything related to the foreign layers being used by Docker on Windows and HCS.
> > Lets say I downloaded a tar/gzip/whatever from mcr.microsoft.com. How do I extract it into a working layer that HCS will accept? How do I handle the data in `PaxHeaders.0`? I can guess, but I'd like to see it documented. Is there anything else that needs to be done?
> 
> You can run `docker pull <image>` to get the layers (they're stored in `%programdata%`) and use them with `wclayer.exe` (from the `hcsshim` example tools). I think this should fully answer your question:
> [microsoft/hcsshim#435 (comment)](https://github.com/microsoft/hcsshim/issues/435#issuecomment-455774190)

Hi，I am a student for WOCW，I have a simple question.
Can I use hcsshim to manage or update windows container which created by Windows Docker?

**Comment by chuchu** [comment]
> Just a quick update: our engineering team is in the process of documenting the HCS C APIs; however there is no plan to further maintain or document the .NET wrapper. In fact, there will be limited documentation on Docker/Moby related APIs going forward. We are transitioning from Docker/Moby to containerD, hence I'd suggest the community to transition with us and leverage those higher level abstraction layers.

@weijuans-msft What do you mean with this transition? I thought that containerd is something what is used by moby.

**Comment by TBBle** [comment]
Based on what's happened since then, I believe what @weijuans-msft meant was that the API _used_ in Docker/Moby (i.e. the HCS v1 API in vmcompute.dll wrapped to Go via hcsshim and for .NET via [dotnet-computevirtualization](https://github.com/microsoft/dotnet-computevirtualization)) are being replaced in Docker/Moby by using containerd, which itself uses hcsshim, and which wraps HCS v1 *and* the successor APIs.

The successor APIs (such as computestorage.dll) _are_ documented in the Windows Platform SDK headers, and were initially available in Windows Server 2019 and Windows 10 1809, but are still being improved and evolved with ongoing Windows releases.
