### ISSUE TITLE
BSOD occurs when deploying windows containers

### ISSUE THREAD

**Issue by nandhu31** [microsoft/Windows-Containers#470]
I have a Kubernetes cluster which consists of linux and windows nodes. 
When I tried to apply the deployment, BSOD in occuring on windows node. 

When I checked the dump file, get the following error.

SYMBOL_NAME:  nt!CcUninitializeCacheMap+234ac5

MODULE_NAME: nt

IMAGE_NAME:  ntkrnlmp.exe

STACK_COMMAND:  .cxr; .ecxr ; kb

BUCKET_ID_FUNC_OFFSET:  234ac5

FAILURE_BUCKET_ID:  0x34_nt!CcUninitializeCacheMap

OS_VERSION:  10.0.20348.859

BUILDLAB_STR:  fe_release_svc_prod2

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {8e05a99b-1bec-5629-33ce-0f8c05cbbfc6}

Followup:     MachineOwner

**Comment by ntrappe-msft** [comment]
Hi, since this is a Kubernetes cluster and I'm assuming you're running it on AKS, have you tried to raise this issue with the AKS team first? If it's a problem with a deployment, it's more likely to be a result of that. We typically handle issues specific to the containers themselves rather than the deployment/servicing at scale.

**Comment by fady-azmy-msft** [comment]
Closing issue because it's going stale.
