### ISSUE TITLE
Provide base image for windows containers - < 100 MB

### ISSUE THREAD

**Issue by prabh-62** [microsoft/Windows-Containers#57]
Original Thread: https://github.com/dotnet/dotnet-docker/issues/2257

- `nanoserver:2004(amd)` - `262 MB`
- `nanoserver:1909(amd` - `256 MB`
- `nanoserver:sac2016` - `1171 MB`

Microsoft recommends [smaller docker image sizes](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-faq#how-can-i-speed-up-the-deployment-of-my-container) and alpine variant of Windows would help with faster deployments and cold starts

**Comment by immuzz** [comment]
Thank you @prabh-62 for the feedback. This is something we are continuously looking at and seriously considering for long-term but its not something that could be done in a short-term, due to physical limitation of how much small we could make different components in the image while providing all the critical Windows features so you could run .NET.
