### ISSUE TITLE
Docker "Windows Error Reporting" crash dump for StackOverflowExceptions not wokring

### ISSUE THREAD

**Issue by alexis-spx** [microsoft/Windows-Containers#60]
I am not sure if I have missed some sort of configuration or something, but I cannot seem to get windows error reporting to create a dump file when a dotnet application crashes with a stack overflow or out of memory exception in a windows docker container.  With the same configuration added to my local machine these dump files are created as expected.

I have created a minimum repo here https://github.com/spreadex/win-docker-crash-dump which demonstrates the configuration used and the resulting lack of dump file.

In summary I create the following registry entries

```
$key = "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\{0}" -f myapp.exe
New-Item $key -Force
Push-Location $key
New-ItemProperty . -Name DumpType -Value 2 -PropertyType DWord
New-ItemProperty . -Name DumpFolder -Value "C:\Dumps" -PropertyType String
Pop-Location

```
When I run it I map a volume on the host to C:\Dumps, a dump is created when an unhandled user exception is thrown, but not when a stack overflow or out of memory exception is thrown.

I am not sure if this is a bug or I am missing some configuration somewhere, but any help would be apricated.

**Comment by brasmith-ms** [comment]
Hi @alexis-spx we're currently investigating this issue from our side and aim to have an answer for you as soon as possible. If you have any additional logs or data available feel free to add them here.

**Comment by zhiweiv** [comment]
Any update? 

We have an daemon process to create child process in container, the child process crashed without dump generated, the console output of child process is:
`Process is terminated due to StackOverflowException.`

The process is .net framework app, procdump is used as dump collector.
```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2-20201110-windowsservercore-ltsc2019

COPY procdump64.exe /dump/
RUN /dump/procdump64.exe -accepteula -i C:/dump
```

It is hard to troubleshooting StackOverflowException without dump.

**Comment by AlanAuerbachMSFT** [comment]
Thanks for the issue report.  We've confirmed that this is a bug.

As a workaround, you can configure the Windows Error Reporting Service (WerSvc) to Startup Type = Automatic.

**Comment by zhiweiv** [comment]
I will try the workaround. BTW any plan for the bug fixing?

**Comment by zhiweiv** [comment]
The workaround doesn't work, dump for StackOverflowException not generated after start set WerSvc StartType=Automatic and Status=Running in container manually.

**Comment by AlanAuerbachMSFT** [comment]
Sorry, I wasn't clear about where to set WerSvc to automatic start (& running).  That needs to happen in the host context, not the container context.  (The bug is that the failfast codepath performs a check for WerSvc running in host context even though it uses WerSvc running in the container context.  Setting WerSvc to automatic in host context keeps it running and satisfies the check, which makes the workaround work.)

**Comment by mmagrum** [comment]
This is a bigger issue than just the WerSvc as the StackOverflowException errors are not showing up in the event viewer either. I created an application that throws a stack overflow when you click a button and loaded it into a 2016 LTSC container and it both created the crash dump and had the appropriate error in the event viewer. When used the exact same dockerfile (only changing the windows version) to 2019 1809 LTSC container it neither created a crash dump nor did it display any error in event viewer (it did, however, crash the app pool and leave the application in a non-functional state just like in 2016 so it would appear it did indeed have a StackOverflowException). I duplicated this with 1909 SAC and 2004 SAC, trying all with and without starting WerSvc on my local and the container, both with the same disappointing results of no crash dumps or error messages. It would appear that the root cause may have to do with how IIS is handling the errors and them not pushing the errors to the container's event viewer. I did also check the host event viewer and they are also not in there.

**Comment by johannordincab** [comment]
@AlanAuerbachMSFT could you give a more detailed example on how to solve this?

**Comment by johannordincab** [comment]
@zhiweiv did you get it working? would love some instructions <3

**Comment by zhiweiv** [comment]
I tried latest workaround, still not working.

Sent from my iPhone
________________________________

**Comment by AlanAuerbachMSFT** [comment]
The sample in the original post uses process isolation, which is how I validated the workaround. It won't work with hyper-v isolation. Which isolation level are y'all using?

**Comment by zhiweiv** [comment]
I tried it in AKS Windows nodes, it is process isolation. I enabled WerSvc in host vm and inside container both, then ran the program crashed with StackOverflow inside container, crash dump still not found in container or host vm.

Since you have validated it should work, I will try again when available.

**Comment by johannordincab** [comment]
We are in the same situation @zhiweiv , we are pretty far in migrating our onprem to aks but stumbled upon this problem. @AlanAuerbachMSFT do you know if there is a solution for AKS?

**Comment by AlanAuerbachMSFT** [comment]
The first thing we have to do is to make sure we're all describing the same problem.  If you refer back to the https://github.com/spreadex/win-docker-crash-dump repo, you'll notice that run-container.ps1 takes an argument.  If the "ue" argument produces a dump for you and the "so" argument does not, then you're seeing the issue described here.  If the "ue" argument does not produce a dump for you, then you've got a different issue.

Once you've verified that you're not encountering a different issue, then to test the workaround, make sure that you are using process isolation and not hyper-v isolation in the "docker run" command.

Finally, as far as fix release is concerned, I've submitted a fix into the hopper.  @brasmith-ms would then be able to better communicate when to expect that fix to appear in an image update.

**Comment by zhiweiv** [comment]
In my case, I confirmed **ue** dump were collected, **so** were not. I will verify the workaround again.

+1 for the fix release.

**Comment by mmagrum** [comment]
Yep, I was testing this process on my local machine to see if it worked and was thereby using Hyper-V isolation. When I loaded my app into our test kubernetes cluster and turned on WerSvc on the node that was hosting the container and went to my crash page, I got a crash dump and the crash showed up in the container error log. When I stopped WerSvc on the host node, it did not generate a crash dump. The workaround works for me then!

**Comment by AlanAuerbachMSFT** [comment]
It's possible, though cumbersome, to apply the workaround in the Hyper-V isolation case as well.  The trick is to get the UtilityVM to autostart WerSvc.  I don't recommend this for production scenarios, but I'll mention it here anyway.

(You can use “docker inspect” on the imageID that you’re interested in to find the path to the image's base layer.)

### Configure WerSvc to autostart in the utility VM
 
```
reg load HKLM\UVM C:\ProgramData\Docker\windowsfilter\<hash-of-image-base-layer*>\UtilityVM\Files\Windows\System32\config\SYSTEM
reg add HKLM\UVM\ControlSet001\Services\WerSvc /v Start /t REG_DWORD /d 2 /f
reg unload HKLM\UVM

```
 ### Reboot
I believe a full reboot is needed to get the UtilityVM to restart with the registry change.

**Comment by ericsegelbergcab** [comment]
I work in the same team as @johannordincab and I can confirm that we experience the same problems described here.

We have recreated the issue using the spreadex crash code. Running the application with the user exception argument creates a dump but no dump is created for the stack overflow exception.
The dump is created without any problems after we reconfigured wersvc with StartupType Automatic and started it on both the Windows node and the container.

So the workaround seems to do the job.

But we need help here to find out how to make this work for a production environment. Is there a way to script this for our nodes? Scaling out creates new nodes and we need to configure them correctly as well.

@AlanAuerbachMSFT, do you know some with aks knowledge that can help us out?

**Comment by zhiweiv** [comment]
> Finally, as far as fix release is concerned, I've submitted a fix into the hopper. @brasmith-ms would then be able to better communicate when to expect that fix to appear in an image update.

Any update on this?

**Comment by brasmith-ms** [comment]
Hi folks, @zhiweiv apologies missed the notification on this. The fix has been checked in and is scheduled for servicing for the 6C timeframe. Container images are published on patch Tuesdays (B releases), so the container image containing this fix will be available via MCR on patch Tuesday in July (7B, the 13th). If you have any questions please feel free to reach out to me.
