### ISSUE TITLE
[feature] Support containerd as container runtime in AKS-HCI

### ISSUE THREAD

**Issue by msjingli** [microsoft/Windows-Containers#66]
Currently container runtime is docker, we'd like to move container run time to containerd.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@msjingli, please provide an update or close this issue.

**Comment by msjingli** [comment]
We're actively working on it, goal for preview is 2021 H2.

**Comment by cwilhit** [comment]
Update: we have launched containerd in preview as a container runtime for Windows nodes on AKS-HCI. See documentation here for instructions: https://docs.microsoft.com/en-us/azure-stack/aks-hci/use-containerd-on-windows-aks.

Once it reaches GA, we will close this issue.

**Comment by TBBle** [comment]
The link in https://github.com/microsoft/Windows-Containers/issues/66#issuecomment-1067057040 doesn't appear to exist anymore. Did this quietly hit GA? I assume not, since [the currently supported k8s version list](https://learn.microsoft.com/en-us/azure-stack/aks-hci/supported-kubernetes-versions#aks-on-azure-stack-hci-and-windows-server-kubernetes-release-calendar) notably stops at v1.23, i.e. the last release with dockershim in kubelet.

**Comment by fady-azmy-msft** [comment]
Hey @TBBle, thank you for the reminder that I need to close the ticket. 

We actually did GA containerd for Windows Worker nodes in Aug (see [AKS-HCI blog](https://techcommunity.microsoft.com/t5/azure-stack-blog/aks-on-azure-stack-hci-and-windows-server-september-2022-update/ba-p/3650525), and [release notes](https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2208)).
