### ISSUE TITLE
Adding Support for AD-Domain-Services

### ISSUE THREAD

**Issue by aolszowka** [microsoft/Windows-Containers#91]
I am trying to create a throw away environment for testing management script of an Active Directory Forest. A container seems like the perfect solution for this.

This container would need the `AD-Domain-Services` feature, however it appears that this feature has been removed from the 

Here is my dockerfile:

```dockerfile
FROM microsoft/windowsservercore:1909

RUN powershell -Command Add-WindowsFeature AD-Domain-Services 
```

This fails with the following error:

```
Install-WindowsFeature : The request to add or remove features on the specified server failed.
Installation of one or more roles, role services, or features failed.
The source files could not be found.
Use the "Source" option to specify the location of the files that are required to restore the feature. For more information on specifying a source location, see http://go.microsoft.com/fwlink/?LinkId=243077. Error: 0x800f081f
At line:1 char:1
+ Install-WindowsFeature AD-Domain-Services
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Vhd=; Credent...Name=localhost}:PSObject) [Install-WindowsFeature], Exception
    + FullyQualifiedErrorId : DISMAPI_Error__Failed_To_Enable_Updates,Microsoft.Windows.ServerManager.Commands.AddWindowsFeatureCommand
```

I have tried various source medias to add the feature back in, is there a documented way to add missing features back to these container images?

**Comment by vrapolinario** [comment]
ADDS is not supported on Windows Containers given container's management nature. We do support gMSA for applications that need AD support.

One question is if this can be solved by installing the appropriate PowerShell module for AD management (haven't tried that myself). However, if the scripting really needs ADDS running in Windows Containers, this is not a scenario we intend to pursue anytime soon.

**Comment by aolszowka** [comment]
So the idea is that you have a "throw away" Domain setup in a container, you are testing your various scripts (IE `Remove-ADUser` / `Remove-GPO`, etc) to ensure your logic before throwing it into production.

Right now the work around I have is spinning up a vagrant image that setups AD (`Install-WindowsFeature AD-Domain-Services ` / `Install-ADDSForest`/`New-ADUser`/`New-ADOrganizationalUnit`/etc) this is SUPER HEAVY as compared to what a container could/should be.

Support gMSA works for the consumer/client side of the Client, however if you're trying to test your AD Setup proper seems like you're outta luck.

Any chance to reconsider or a work around? Is there a hard technical limitation? Thanks for the response!

**Comment by vrapolinario** [comment]
The nature of containers (and microservices) is that you don't have any affinity between a container instance and the application. This is not how AD works. Imagine a scenario on which your container runs and then needs to be recycled. That would not only not work for domain controllers, but also for domain joined server/clients, leaving lingering objects on your AD database.

**Comment by aolszowka** [comment]
> Imagine a scenario on which your container runs and then needs to be recycled. That would not only not work for domain controllers, but also for domain joined server/clients, leaving lingering objects on your AD database.

Correct. However in this case it is exactly what you want, you do not want the Forest to persist after testing has happened, in fact you would be better off if it restored back to the state that it was in the container to allow for testing to be consistent.

**Comment by vrapolinario** [comment]
I see the appeal for using containers in this scenario. We have a more long term area of investigation which includes looking into infrastructure components for Windows containers, but no timeline at this moment.

I'll close the issue as this is not supported today, but please be sure we're taking this feedback very seriously and will definitely consider it as we continue to evolve new scenarios for Windows containers.

**Comment by aolszowka** [comment]
Fair enough thank you for the feedback!

**Comment by ghost** [comment]
huh, I always figured NTDS connectionless ldap was supposed to compliment ndp/ipv6 stateless config in the sense that being a stateless protocol, clients could enumerate enough of active directory (via the broadcast, multicast or LL) to bootstrap into joining a domain without having affinity for a specific container but I guess it's real purpose is just packeting after all.

**Comment by ghost** [comment]
@aolszowka as far as the lingering objects problem is concerned you can probably solve this by storing your ephemeral objects underneath a unique organizational unit each time you want to add new containers, there's a silly number of ways that you can make an organizational unit based hierarchy of containers with varying levels of ephemerality; sorta like managed chaos.... kind of like the whole point of active directory. YMMV, but it's a start for what I'm sure you have in mind is not as unreasonable.

More importantly though, take a look on Google and you will not find people building servercore *base image* containers from dockerfiles anywhere nor are there any instructions on how one might create an installation of server core, create a tarball for `docker import` which sorta in my eyes makes the servercore container a one-off in terms of what bootstrapping a container should actually look like in the real world. I will have to investigate this more but it looks very suspect. Moreover servercore was definitively a thing that one could substantiate NTDS with and if that definition has change then so should the term by which it's defined because: 

```
[ ] Active Directory Domain Services                    AD-Domain-Services               Removed
[ ] Active Directory Federation Services                ADFS-Federation                  Removed
[ ] Active Directory Lightweight Directory Services     ADLDS                            Removed
[ ] Active Directory Rights Management Services         ADRMS                            Removed
```

all that says to me is that this base image sucks and I need to build my own. Although to be perfectly fair with the way Microsoft has been doing things these days; reusing Windows 10 KMS keys for Windows 11? Glad that upgrade is free, I'd be pretty mad come to find out that were the case after spending hundreds of more dollars on am release which likely bears a security flaw that has existed for two or more releases before it. Wouldn't surprise me if the intention is that servercore in a container is not actually servercore at all.

**Comment by ghost** [comment]
@aolszowka I found at least one path, where you need to create a vhd first which you can do pretty quick from a wim using: - https://github.com/clandestinenetworks/communitytools-image2docker-win

if converting a wim to a docker image doesn't work for you then you might try using:
- https://github.com/clandestinenetworks/WindowsImageTools

to convert to vhd first: 

- ` Convert-WIM2VHD -Path c:\disk\server2019core.vhdx -SourcePath c:\server\install.wim -index 3 -Size 40GB -DiskLayout UEFI -Dynamic`

then try converting the VHD to a docker image using the first tool. I don't know about the image2docker-win tool I haven't had a chance to test it yet, but I will find out definitively. To be honest though the rest of the world believes building your own images is vital as opposed to using whatever you can find on docker hub; so it's a good idea to find a way like this to do it anyway.
